//----------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by https://github.com/StefH/ProxyInterfaceSourceGenerator.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//----------------------------------------------------------------------------------------

#nullable enable
using System;

namespace ProxyInterfaceSourceGeneratorTests.Source.PnP
{
    public partial class SecurableObjectProxy : global::ProxyInterfaceSourceGeneratorTests.Source.PnP.ClientObjectProxy, global::ProxyInterfaceSourceGeneratorTests.Source.PnP.ISecurableObject
    {

        private static global::ProxyInterfaceSourceGeneratorTests.Source.PnP.IClientRuntimeContext MapToInterface(global::Microsoft.SharePoint.Client.ClientRuntimeContext value)
        {
            return new global::ProxyInterfaceSourceGeneratorTests.Source.PnP.ClientRuntimeContextProxy(value);
        }

        private static global::ProxyInterfaceSourceGeneratorTests.Source.PnP.IClientObject MapToInterface(global::Microsoft.SharePoint.Client.ClientObject value)
        {
            return new global::ProxyInterfaceSourceGeneratorTests.Source.PnP.ClientObjectProxy(value);
        }

        private static global::ProxyInterfaceSourceGeneratorTests.Source.PnP.ISecurableObject MapToInterface(global::Microsoft.SharePoint.Client.SecurableObject value)
        {
            return new global::ProxyInterfaceSourceGeneratorTests.Source.PnP.SecurableObjectProxy(value);
        }



        public new global::Microsoft.SharePoint.Client.SecurableObject _Instance { get; }
        public global::Microsoft.SharePoint.Client.ClientObject _InstanceClientObject { get; }
        [Microsoft.SharePoint.Client.RemoteAttribute]
        public global::ProxyInterfaceSourceGeneratorTests.Source.PnP.ISecurableObject FirstUniqueAncestorSecurableObject { get => MapToInterface(_Instance.FirstUniqueAncestorSecurableObject); }

        [Microsoft.SharePoint.Client.RemoteAttribute]
        public bool HasUniqueRoleAssignments { get => _Instance.HasUniqueRoleAssignments; }

        [Microsoft.SharePoint.Client.RemoteAttribute]
        public global::Microsoft.SharePoint.Client.RoleAssignmentCollection RoleAssignments { get => _Instance.RoleAssignments; }

        [Microsoft.SharePoint.Client.RemoteAttribute]
        public virtual void ResetRoleInheritance()
        {
            _Instance.ResetRoleInheritance();
        }

        [Microsoft.SharePoint.Client.RemoteAttribute]
        public virtual void BreakRoleInheritance(bool copyRoleAssignments, bool clearSubscopes)
        {
            bool copyRoleAssignments_ = copyRoleAssignments;
            bool clearSubscopes_ = clearSubscopes;
            _Instance.BreakRoleInheritance(copyRoleAssignments_, clearSubscopes_);
        }


        public SecurableObjectProxy(global::Microsoft.SharePoint.Client.SecurableObject instance) : base(instance)
        {
            _Instance = instance;
            _InstanceClientObject = instance;
        }
    }
}
#nullable restore