//----------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by https://github.com/StefH/ProxyInterfaceSourceGenerator.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//----------------------------------------------------------------------------------------

#nullable enable
using System;
using AutoMapper;

namespace ProxyInterfaceSourceGeneratorTests.Source.PnP
{
    public partial class WebProxy : ProxyInterfaceSourceGeneratorTests.Source.PnP.SecurableObjectProxy, IWeb
    {
        public new Microsoft.SharePoint.Client.Web _Instance { get; }
        public new Microsoft.SharePoint.Client.SecurableObject _InstanceBase { get; }


        public string AccessRequestListUrl { get => _Instance.AccessRequestListUrl; }

        public string AccessRequestSiteDescription { get => _Instance.AccessRequestSiteDescription; }

        public string Acronym { get => _Instance.Acronym; }

        public Microsoft.SharePoint.Client.AlertCollection Alerts { get => _Instance.Alerts; }

        public bool AllowAutomaticASPXPageIndexing { get => _Instance.AllowAutomaticASPXPageIndexing; set => _Instance.AllowAutomaticASPXPageIndexing = value; }

        public bool AllowCreateDeclarativeWorkflowForCurrentUser { get => _Instance.AllowCreateDeclarativeWorkflowForCurrentUser; }

        public bool AllowDesignerForCurrentUser { get => _Instance.AllowDesignerForCurrentUser; }

        public bool AllowMasterPageEditingForCurrentUser { get => _Instance.AllowMasterPageEditingForCurrentUser; }

        public bool AllowRevertFromTemplateForCurrentUser { get => _Instance.AllowRevertFromTemplateForCurrentUser; }

        public bool AllowRssFeeds { get => _Instance.AllowRssFeeds; }

        public bool AllowSaveDeclarativeWorkflowAsTemplateForCurrentUser { get => _Instance.AllowSaveDeclarativeWorkflowAsTemplateForCurrentUser; }

        public bool AllowSavePublishDeclarativeWorkflowForCurrentUser { get => _Instance.AllowSavePublishDeclarativeWorkflowForCurrentUser; }

        public Microsoft.SharePoint.Client.PropertyValues AllProperties { get => _Instance.AllProperties; }

        public string AlternateCssUrl { get => _Instance.AlternateCssUrl; set => _Instance.AlternateCssUrl = value; }

        public System.Guid AppInstanceId { get => _Instance.AppInstanceId; }

        public Microsoft.SharePoint.Client.AppTileCollection AppTiles { get => _Instance.AppTiles; }

        public Microsoft.SharePoint.Client.Group AssociatedMemberGroup { get => _Instance.AssociatedMemberGroup; set => _Instance.AssociatedMemberGroup = value; }

        public Microsoft.SharePoint.Client.Group AssociatedOwnerGroup { get => _Instance.AssociatedOwnerGroup; set => _Instance.AssociatedOwnerGroup = value; }

        public Microsoft.SharePoint.Client.Group AssociatedVisitorGroup { get => _Instance.AssociatedVisitorGroup; set => _Instance.AssociatedVisitorGroup = value; }

        public Microsoft.SharePoint.Client.User Author { get => _Instance.Author; }

        public Microsoft.SharePoint.Client.ContentTypeCollection AvailableContentTypes { get => _Instance.AvailableContentTypes; }

        public Microsoft.SharePoint.Client.FieldCollection AvailableFields { get => _Instance.AvailableFields; }

        public Microsoft.SharePoint.Client.ModernizeHomepageResult CanModernizeHomepage { get => _Instance.CanModernizeHomepage; }

        public string ClassicWelcomePage { get => _Instance.ClassicWelcomePage; set => _Instance.ClassicWelcomePage = value; }

        public bool CommentsOnSitePagesDisabled { get => _Instance.CommentsOnSitePagesDisabled; set => _Instance.CommentsOnSitePagesDisabled = value; }

        public short Configuration { get => _Instance.Configuration; }

        public bool ContainsConfidentialInfo { get => _Instance.ContainsConfidentialInfo; set => _Instance.ContainsConfidentialInfo = value; }

        public Microsoft.SharePoint.Client.ContentTypeCollection ContentTypes { get => _Instance.ContentTypes; }

        public System.DateTime Created { get => _Instance.Created; }

        public Microsoft.SharePoint.Client.ChangeToken CurrentChangeToken { get => _Instance.CurrentChangeToken; }

        public Microsoft.SharePoint.Client.User CurrentUser { get => _Instance.CurrentUser; }

        public string CustomMasterUrl { get => _Instance.CustomMasterUrl; set => _Instance.CustomMasterUrl = value; }

        public bool CustomSiteActionsDisabled { get => _Instance.CustomSiteActionsDisabled; set => _Instance.CustomSiteActionsDisabled = value; }

        public Microsoft.SharePoint.Client.SPDataLeakagePreventionStatusInfo DataLeakagePreventionStatusInfo { get => _Instance.DataLeakagePreventionStatusInfo; }

        public string Description { get => _Instance.Description; set => _Instance.Description = value; }

        public string DescriptionForExistingLanguage { get => _Instance.DescriptionForExistingLanguage; set => _Instance.DescriptionForExistingLanguage = value; }

        public Microsoft.SharePoint.Client.UserResource DescriptionResource { get => _Instance.DescriptionResource; }

        public System.Collections.Generic.IEnumerable<Microsoft.SharePoint.Client.SPResourceEntry> DescriptionTranslations { get => _Instance.DescriptionTranslations; set => _Instance.DescriptionTranslations = value; }

        public string DesignerDownloadUrlForCurrentUser { get => _Instance.DesignerDownloadUrlForCurrentUser; }

        public System.Guid DesignPackageId { get => _Instance.DesignPackageId; set => _Instance.DesignPackageId = value; }

        public bool DisableAppViews { get => _Instance.DisableAppViews; set => _Instance.DisableAppViews = value; }

        public bool DisableFlows { get => _Instance.DisableFlows; set => _Instance.DisableFlows = value; }

        public bool DisableRecommendedItems { get => _Instance.DisableRecommendedItems; set => _Instance.DisableRecommendedItems = value; }

        public bool DocumentLibraryCalloutOfficeWebAppPreviewersDisabled { get => _Instance.DocumentLibraryCalloutOfficeWebAppPreviewersDisabled; }

        public Microsoft.SharePoint.Client.BasePermissions EffectiveBasePermissions { get => _Instance.EffectiveBasePermissions; }

        public bool EnableMinimalDownload { get => _Instance.EnableMinimalDownload; set => _Instance.EnableMinimalDownload = value; }

        public Microsoft.SharePoint.Client.EventReceiverDefinitionCollection EventReceivers { get => _Instance.EventReceivers; }

        public bool ExcludeFromOfflineClient { get => _Instance.ExcludeFromOfflineClient; set => _Instance.ExcludeFromOfflineClient = value; }

        public Microsoft.SharePoint.Client.FeatureCollection Features { get => _Instance.Features; }

        public Microsoft.SharePoint.Client.FieldCollection Fields { get => _Instance.Fields; }

        public Microsoft.SharePoint.Client.FolderCollection Folders { get => _Instance.Folders; }

        public Microsoft.SharePoint.Client.FooterVariantThemeType FooterEmphasis { get => _Instance.FooterEmphasis; set => _Instance.FooterEmphasis = value; }

        public bool FooterEnabled { get => _Instance.FooterEnabled; set => _Instance.FooterEnabled = value; }

        public Microsoft.SharePoint.Client.FooterLayoutType FooterLayout { get => _Instance.FooterLayout; set => _Instance.FooterLayout = value; }

        public bool HasWebTemplateExtension { get => _Instance.HasWebTemplateExtension; set => _Instance.HasWebTemplateExtension = value; }

        public Microsoft.SharePoint.Client.SPVariantThemeType HeaderEmphasis { get => _Instance.HeaderEmphasis; set => _Instance.HeaderEmphasis = value; }

        public Microsoft.SharePoint.Client.HeaderLayoutType HeaderLayout { get => _Instance.HeaderLayout; set => _Instance.HeaderLayout = value; }

        public bool HideTitleInHeader { get => _Instance.HideTitleInHeader; set => _Instance.HideTitleInHeader = value; }

        public bool HorizontalQuickLaunch { get => _Instance.HorizontalQuickLaunch; set => _Instance.HorizontalQuickLaunch = value; }

        public Microsoft.SharePoint.ClientSideComponent.HostedAppsManager HostedApps { get => _Instance.HostedApps; }

        public System.Guid Id { get => _Instance.Id; }

        public bool IsEduClass { get => _Instance.IsEduClass; }

        public bool IsEduClassProvisionChecked { get => _Instance.IsEduClassProvisionChecked; }

        public bool IsEduClassProvisionPending { get => _Instance.IsEduClassProvisionPending; }

        public bool IsHomepageModernized { get => _Instance.IsHomepageModernized; }

        public bool IsMultilingual { get => _Instance.IsMultilingual; set => _Instance.IsMultilingual = value; }

        public bool IsProvisioningComplete { get => _Instance.IsProvisioningComplete; }

        public bool IsRevertHomepageLinkHidden { get => _Instance.IsRevertHomepageLinkHidden; set => _Instance.IsRevertHomepageLinkHidden = value; }

        public uint Language { get => _Instance.Language; }

        public System.DateTime LastItemModifiedDate { get => _Instance.LastItemModifiedDate; }

        public System.DateTime LastItemUserModifiedDate { get => _Instance.LastItemUserModifiedDate; }

        public Microsoft.SharePoint.Client.ListCollection Lists { get => _Instance.Lists; }

        public Microsoft.SharePoint.Client.ListTemplateCollection ListTemplates { get => _Instance.ListTemplates; }

        public Microsoft.SharePoint.Client.LogoAlignment LogoAlignment { get => _Instance.LogoAlignment; set => _Instance.LogoAlignment = value; }

        public string MasterUrl { get => _Instance.MasterUrl; set => _Instance.MasterUrl = value; }

        public bool MegaMenuEnabled { get => _Instance.MegaMenuEnabled; set => _Instance.MegaMenuEnabled = value; }

        public bool MembersCanShare { get => _Instance.MembersCanShare; set => _Instance.MembersCanShare = value; }

        public bool NavAudienceTargetingEnabled { get => _Instance.NavAudienceTargetingEnabled; set => _Instance.NavAudienceTargetingEnabled = value; }

        public Microsoft.SharePoint.Client.Navigation Navigation { get => _Instance.Navigation; }

        public bool NextStepsFirstRunEnabled { get => _Instance.NextStepsFirstRunEnabled; set => _Instance.NextStepsFirstRunEnabled = value; }

        public bool NoCrawl { get => _Instance.NoCrawl; set => _Instance.NoCrawl = value; }

        public bool NotificationsInOneDriveForBusinessEnabled { get => _Instance.NotificationsInOneDriveForBusinessEnabled; }

        public bool NotificationsInSharePointEnabled { get => _Instance.NotificationsInSharePointEnabled; }

        public bool ObjectCacheEnabled { get => _Instance.ObjectCacheEnabled; set => _Instance.ObjectCacheEnabled = value; }

        public bool OverwriteTranslationsOnChange { get => _Instance.OverwriteTranslationsOnChange; set => _Instance.OverwriteTranslationsOnChange = value; }

        public Microsoft.SharePoint.Client.WebInformation ParentWeb { get => _Instance.ParentWeb; }

        public Microsoft.SharePoint.Client.ResourcePath ResourcePath { get => _Instance.ResourcePath; }

        public bool PreviewFeaturesEnabled { get => _Instance.PreviewFeaturesEnabled; }

        public string PrimaryColor { get => _Instance.PrimaryColor; }

        public Microsoft.SharePoint.Client.PushNotificationSubscriberCollection PushNotificationSubscribers { get => _Instance.PushNotificationSubscribers; }

        public bool QuickLaunchEnabled { get => _Instance.QuickLaunchEnabled; set => _Instance.QuickLaunchEnabled = value; }

        public Microsoft.SharePoint.Client.RecycleBinItemCollection RecycleBin { get => _Instance.RecycleBin; }

        public bool RecycleBinEnabled { get => _Instance.RecycleBinEnabled; }

        public Microsoft.SharePoint.Client.RegionalSettings RegionalSettings { get => _Instance.RegionalSettings; }

        public string RequestAccessEmail { get => _Instance.RequestAccessEmail; set => _Instance.RequestAccessEmail = value; }

        public Microsoft.SharePoint.Client.RoleDefinitionCollection RoleDefinitions { get => _Instance.RoleDefinitions; }

        public Microsoft.SharePoint.Client.Folder RootFolder { get => _Instance.RootFolder; }

        public bool SaveSiteAsTemplateEnabled { get => _Instance.SaveSiteAsTemplateEnabled; set => _Instance.SaveSiteAsTemplateEnabled = value; }

        public Microsoft.SharePoint.Client.SearchBoxInNavBarType SearchBoxInNavBar { get => _Instance.SearchBoxInNavBar; set => _Instance.SearchBoxInNavBar = value; }

        public string SearchBoxPlaceholderText { get => _Instance.SearchBoxPlaceholderText; set => _Instance.SearchBoxPlaceholderText = value; }

        public Microsoft.SharePoint.Client.SearchScopeType SearchScope { get => _Instance.SearchScope; set => _Instance.SearchScope = value; }

        public Microsoft.SharePoint.Client.ResourcePath ServerRelativePath { get => _Instance.ServerRelativePath; }

        public string ServerRelativeUrl { get => _Instance.ServerRelativeUrl; set => _Instance.ServerRelativeUrl = value; }

        public bool ShowUrlStructureForCurrentUser { get => _Instance.ShowUrlStructureForCurrentUser; }

        public Microsoft.SharePoint.Marketplace.CorporateCuratedGallery.SiteCollectionCorporateCatalogAccessor SiteCollectionAppCatalog { get => _Instance.SiteCollectionAppCatalog; }

        public Microsoft.SharePoint.Client.GroupCollection SiteGroups { get => _Instance.SiteGroups; }

        public string SiteLogoDescription { get => _Instance.SiteLogoDescription; set => _Instance.SiteLogoDescription = value; }

        public string SiteLogoUrl { get => _Instance.SiteLogoUrl; set => _Instance.SiteLogoUrl = value; }

        public Microsoft.SharePoint.Client.List SiteUserInfoList { get => _Instance.SiteUserInfoList; }

        public Microsoft.SharePoint.Client.UserCollection SiteUsers { get => _Instance.SiteUsers; }

        public System.Collections.Generic.IEnumerable<int> SupportedUILanguageIds { get => _Instance.SupportedUILanguageIds; set => _Instance.SupportedUILanguageIds = value; }

        public bool SyndicationEnabled { get => _Instance.SyndicationEnabled; set => _Instance.SyndicationEnabled = value; }

        public Microsoft.SharePoint.Client.SharingState TenantAdminMembersCanShare { get => _Instance.TenantAdminMembersCanShare; }

        public Microsoft.SharePoint.Marketplace.CorporateCuratedGallery.TenantCorporateCatalogAccessor TenantAppCatalog { get => _Instance.TenantAppCatalog; }

        public bool TenantTagPolicyEnabled { get => _Instance.TenantTagPolicyEnabled; }

        public string ThemedCssFolderUrl { get => _Instance.ThemedCssFolderUrl; set => _Instance.ThemedCssFolderUrl = value; }

        public Microsoft.SharePoint.Client.ThemeInfo ThemeInfo { get => _Instance.ThemeInfo; }

        public bool ThirdPartyMdmEnabled { get => _Instance.ThirdPartyMdmEnabled; }

        public string Title { get => _Instance.Title; set => _Instance.Title = value; }

        public string TitleForExistingLanguage { get => _Instance.TitleForExistingLanguage; set => _Instance.TitleForExistingLanguage = value; }

        public Microsoft.SharePoint.Client.UserResource TitleResource { get => _Instance.TitleResource; }

        public System.Collections.Generic.IEnumerable<Microsoft.SharePoint.Client.SPResourceEntry> TitleTranslations { get => _Instance.TitleTranslations; set => _Instance.TitleTranslations = value; }

        public bool TreeViewEnabled { get => _Instance.TreeViewEnabled; set => _Instance.TreeViewEnabled = value; }

        public int UIVersion { get => _Instance.UIVersion; set => _Instance.UIVersion = value; }

        public bool UIVersionConfigurationEnabled { get => _Instance.UIVersionConfigurationEnabled; set => _Instance.UIVersionConfigurationEnabled = value; }

        public string Url { get => _Instance.Url; }

        public bool UseAccessRequestDefault { get => _Instance.UseAccessRequestDefault; }

        public Microsoft.SharePoint.Client.UserCustomActionCollection UserCustomActions { get => _Instance.UserCustomActions; }

        public Microsoft.SharePoint.Client.WebCollection Webs { get => _Instance.Webs; }

        public string WebTemplate { get => _Instance.WebTemplate; }

        public string WebTemplateConfiguration { get => _Instance.WebTemplateConfiguration; }

        public bool WebTemplatesGalleryFirstRunEnabled { get => _Instance.WebTemplatesGalleryFirstRunEnabled; set => _Instance.WebTemplatesGalleryFirstRunEnabled = value; }

        public string WelcomePage { get => _Instance.WelcomePage; }

        public Microsoft.SharePoint.Client.Workflow.WorkflowAssociationCollection WorkflowAssociations { get => _Instance.WorkflowAssociations; }

        public Microsoft.SharePoint.Client.Workflow.WorkflowTemplateCollection WorkflowTemplates { get => _Instance.WorkflowTemplates; }



        public System.Uri WebUrlFromPageUrlDirect(ProxyInterfaceSourceGeneratorTests.Source.PnP.IClientContext context, System.Uri pageFullUrl)
        {
            Microsoft.SharePoint.Client.ClientContext context_ = _mapper.Map<Microsoft.SharePoint.Client.ClientContext>(context);
            System.Uri pageFullUrl_ = pageFullUrl;
            var result__258107370 = Microsoft.SharePoint.Client.Web.WebUrlFromPageUrlDirect(context_, pageFullUrl_);
            return result__258107370;
        }

        public System.Uri WebUrlFromFolderUrlDirect(ProxyInterfaceSourceGeneratorTests.Source.PnP.IClientContext context, System.Uri folderFullUrl)
        {
            Microsoft.SharePoint.Client.ClientContext context_ = _mapper.Map<Microsoft.SharePoint.Client.ClientContext>(context);
            System.Uri folderFullUrl_ = folderFullUrl;
            var result_21992317 = Microsoft.SharePoint.Client.Web.WebUrlFromFolderUrlDirect(context_, folderFullUrl_);
            return result_21992317;
        }

        public Microsoft.SharePoint.Client.ClientResult<bool> DoesUserHavePermissions(Microsoft.SharePoint.Client.BasePermissions permissionMask)
        {
            Microsoft.SharePoint.Client.BasePermissions permissionMask_ = permissionMask;
            var result_563212462 = _Instance.DoesUserHavePermissions(permissionMask_);
            return result_563212462;
        }

        public Microsoft.SharePoint.Client.ClientResult<Microsoft.SharePoint.Client.BasePermissions> GetUserEffectivePermissions(string userName)
        {
            string userName_ = userName;
            var result__615383406 = _Instance.GetUserEffectivePermissions(userName_);
            return result__615383406;
        }

        public void CreateDefaultAssociatedGroups(string userLogin, string userLogin2, string groupNameSeed)
        {
            string userLogin_ = userLogin;
            string userLogin2_ = userLogin2;
            string groupNameSeed_ = groupNameSeed;
            _Instance.CreateDefaultAssociatedGroups(userLogin_, userLogin2_, groupNameSeed_);
        }

        public Microsoft.SharePoint.Client.ClientResult<string> CreateOrganizationSharingLink(ProxyInterfaceSourceGeneratorTests.Source.PnP.IClientRuntimeContext context, string url, bool isEditLink)
        {
            Microsoft.SharePoint.Client.ClientRuntimeContext context_ = _mapper.Map<Microsoft.SharePoint.Client.ClientRuntimeContext>(context);
            string url_ = url;
            bool isEditLink_ = isEditLink;
            var result_2070260011 = Microsoft.SharePoint.Client.Web.CreateOrganizationSharingLink(context_, url_, isEditLink_);
            return result_2070260011;
        }

        public void DestroyOrganizationSharingLink(ProxyInterfaceSourceGeneratorTests.Source.PnP.IClientRuntimeContext context, string url, bool isEditLink, bool removeAssociatedSharingLinkGroup)
        {
            Microsoft.SharePoint.Client.ClientRuntimeContext context_ = _mapper.Map<Microsoft.SharePoint.Client.ClientRuntimeContext>(context);
            string url_ = url;
            bool isEditLink_ = isEditLink;
            bool removeAssociatedSharingLinkGroup_ = removeAssociatedSharingLinkGroup;
            Microsoft.SharePoint.Client.Web.DestroyOrganizationSharingLink(context_, url_, isEditLink_, removeAssociatedSharingLinkGroup_);
        }

        public Microsoft.SharePoint.Client.ClientResult<Microsoft.SharePoint.Client.SharingLinkKind> GetSharingLinkKind(ProxyInterfaceSourceGeneratorTests.Source.PnP.IClientRuntimeContext context, string fileUrl)
        {
            Microsoft.SharePoint.Client.ClientRuntimeContext context_ = _mapper.Map<Microsoft.SharePoint.Client.ClientRuntimeContext>(context);
            string fileUrl_ = fileUrl;
            var result_654626020 = Microsoft.SharePoint.Client.Web.GetSharingLinkKind(context_, fileUrl_);
            return result_654626020;
        }

        public Microsoft.SharePoint.Client.ClientResult<Microsoft.SharePoint.Client.SharingLinkData> GetSharingLinkData(string linkUrl)
        {
            string linkUrl_ = linkUrl;
            var result__2107757018 = _Instance.GetSharingLinkData(linkUrl_);
            return result__2107757018;
        }

        public Microsoft.SharePoint.Client.ClientResult<string> MapToIcon(string fileName, string progId, Microsoft.SharePoint.Client.Utilities.IconSize size)
        {
            string fileName_ = fileName;
            string progId_ = progId;
            Microsoft.SharePoint.Client.Utilities.IconSize size_ = size;
            var result_384589064 = _Instance.MapToIcon(fileName_, progId_, size_);
            return result_384589064;
        }

        public Microsoft.SharePoint.Client.ClientResult<string> GetWebUrlFromPageUrl(ProxyInterfaceSourceGeneratorTests.Source.PnP.IClientRuntimeContext context, string pageFullUrl)
        {
            Microsoft.SharePoint.Client.ClientRuntimeContext context_ = _mapper.Map<Microsoft.SharePoint.Client.ClientRuntimeContext>(context);
            string pageFullUrl_ = pageFullUrl;
            var result__907059837 = Microsoft.SharePoint.Client.Web.GetWebUrlFromPageUrl(context_, pageFullUrl_);
            return result__907059837;
        }

        public Microsoft.SharePoint.Client.PushNotificationSubscriber RegisterPushNotificationSubscriber(System.Guid deviceAppInstanceId, string serviceToken)
        {
            System.Guid deviceAppInstanceId_ = deviceAppInstanceId;
            string serviceToken_ = serviceToken;
            var result__117534630 = _Instance.RegisterPushNotificationSubscriber(deviceAppInstanceId_, serviceToken_);
            return result__117534630;
        }

        public void UnregisterPushNotificationSubscriber(System.Guid deviceAppInstanceId)
        {
            System.Guid deviceAppInstanceId_ = deviceAppInstanceId;
            _Instance.UnregisterPushNotificationSubscriber(deviceAppInstanceId_);
        }

        public Microsoft.SharePoint.Client.PushNotificationSubscriberCollection GetPushNotificationSubscribersByArgs(string customArgs)
        {
            string customArgs_ = customArgs;
            var result_144086076 = _Instance.GetPushNotificationSubscribersByArgs(customArgs_);
            return result_144086076;
        }

        public Microsoft.SharePoint.Client.PushNotificationSubscriberCollection GetPushNotificationSubscribersByUser(string userName)
        {
            string userName_ = userName;
            var result__1280834962 = _Instance.GetPushNotificationSubscribersByUser(userName_);
            return result__1280834962;
        }

        public Microsoft.SharePoint.Client.ClientResult<bool> DoesPushNotificationSubscriberExist(System.Guid deviceAppInstanceId)
        {
            System.Guid deviceAppInstanceId_ = deviceAppInstanceId;
            var result__1309404561 = _Instance.DoesPushNotificationSubscriberExist(deviceAppInstanceId_);
            return result__1309404561;
        }

        public Microsoft.SharePoint.Client.PushNotificationSubscriber GetPushNotificationSubscriber(System.Guid deviceAppInstanceId)
        {
            System.Guid deviceAppInstanceId_ = deviceAppInstanceId;
            var result_1696633571 = _Instance.GetPushNotificationSubscriber(deviceAppInstanceId_);
            return result_1696633571;
        }

        public Microsoft.SharePoint.Client.User GetSiteUserIncludingDeletedByPuid(string puid)
        {
            string puid_ = puid;
            var result__1448181221 = _Instance.GetSiteUserIncludingDeletedByPuid(puid_);
            return result__1448181221;
        }

        public Microsoft.SharePoint.Client.User GetUserById(int userId)
        {
            int userId_ = userId;
            var result__963170767 = _Instance.GetUserById(userId_);
            return result__963170767;
        }

        public Microsoft.SharePoint.Client.ClientResult<bool> EnsureTenantAppCatalog(string callerId)
        {
            string callerId_ = callerId;
            var result__1044639826 = _Instance.EnsureTenantAppCatalog(callerId_);
            return result__1044639826;
        }

        public Microsoft.SharePoint.ClientSideComponent.StorageEntity GetStorageEntity(string key)
        {
            string key_ = key;
            var result__1529029872 = _Instance.GetStorageEntity(key_);
            return result__1529029872;
        }

        public void SetStorageEntity(string key, string value, string description, string comments)
        {
            string key_ = key;
            string value_ = value;
            string description_ = description;
            string comments_ = comments;
            _Instance.SetStorageEntity(key_, value_, description_, comments_);
        }

        public void RemoveStorageEntity(string key)
        {
            string key_ = key;
            _Instance.RemoveStorageEntity(key_);
        }

        public Microsoft.SharePoint.Client.SharingResult ShareObject(ProxyInterfaceSourceGeneratorTests.Source.PnP.IClientRuntimeContext context, string url, string peoplePickerInput, string roleValue, int groupId, bool propagateAcl, bool sendEmail, bool includeAnonymousLinkInEmail, string emailSubject, string emailBody, bool useSimplifiedRoles)
        {
            Microsoft.SharePoint.Client.ClientRuntimeContext context_ = _mapper.Map<Microsoft.SharePoint.Client.ClientRuntimeContext>(context);
            string url_ = url;
            string peoplePickerInput_ = peoplePickerInput;
            string roleValue_ = roleValue;
            int groupId_ = groupId;
            bool propagateAcl_ = propagateAcl;
            bool sendEmail_ = sendEmail;
            bool includeAnonymousLinkInEmail_ = includeAnonymousLinkInEmail;
            string emailSubject_ = emailSubject;
            string emailBody_ = emailBody;
            bool useSimplifiedRoles_ = useSimplifiedRoles;
            var result_816157054 = Microsoft.SharePoint.Client.Web.ShareObject(context_, url_, peoplePickerInput_, roleValue_, groupId_, propagateAcl_, sendEmail_, includeAnonymousLinkInEmail_, emailSubject_, emailBody_, useSimplifiedRoles_);
            return result_816157054;
        }

        public Microsoft.SharePoint.Client.SharingResult ForwardObjectLink(ProxyInterfaceSourceGeneratorTests.Source.PnP.IClientRuntimeContext context, string url, string peoplePickerInput, string emailSubject, string emailBody)
        {
            Microsoft.SharePoint.Client.ClientRuntimeContext context_ = _mapper.Map<Microsoft.SharePoint.Client.ClientRuntimeContext>(context);
            string url_ = url;
            string peoplePickerInput_ = peoplePickerInput;
            string emailSubject_ = emailSubject;
            string emailBody_ = emailBody;
            var result__1822800612 = Microsoft.SharePoint.Client.Web.ForwardObjectLink(context_, url_, peoplePickerInput_, emailSubject_, emailBody_);
            return result__1822800612;
        }

        public Microsoft.SharePoint.Client.SharingResult UnshareObject(ProxyInterfaceSourceGeneratorTests.Source.PnP.IClientRuntimeContext context, string url)
        {
            Microsoft.SharePoint.Client.ClientRuntimeContext context_ = _mapper.Map<Microsoft.SharePoint.Client.ClientRuntimeContext>(context);
            string url_ = url;
            var result__823224569 = Microsoft.SharePoint.Client.Web.UnshareObject(context_, url_);
            return result__823224569;
        }

        public Microsoft.SharePoint.Client.ObjectSharingSettings GetObjectSharingSettings(ProxyInterfaceSourceGeneratorTests.Source.PnP.IClientRuntimeContext context, string objectUrl, int groupId, bool useSimplifiedRoles)
        {
            Microsoft.SharePoint.Client.ClientRuntimeContext context_ = _mapper.Map<Microsoft.SharePoint.Client.ClientRuntimeContext>(context);
            string objectUrl_ = objectUrl;
            int groupId_ = groupId;
            bool useSimplifiedRoles_ = useSimplifiedRoles;
            var result__679475674 = Microsoft.SharePoint.Client.Web.GetObjectSharingSettings(context_, objectUrl_, groupId_, useSimplifiedRoles_);
            return result__679475674;
        }

        public Microsoft.SharePoint.Client.ClientResult<string> CreateAnonymousLink(ProxyInterfaceSourceGeneratorTests.Source.PnP.IClientRuntimeContext context, string url, bool isEditLink)
        {
            Microsoft.SharePoint.Client.ClientRuntimeContext context_ = _mapper.Map<Microsoft.SharePoint.Client.ClientRuntimeContext>(context);
            string url_ = url;
            bool isEditLink_ = isEditLink;
            var result__820192309 = Microsoft.SharePoint.Client.Web.CreateAnonymousLink(context_, url_, isEditLink_);
            return result__820192309;
        }

        public Microsoft.SharePoint.Client.ClientResult<string> CreateAnonymousLinkWithExpiration(ProxyInterfaceSourceGeneratorTests.Source.PnP.IClientRuntimeContext context, string url, bool isEditLink, string expirationString)
        {
            Microsoft.SharePoint.Client.ClientRuntimeContext context_ = _mapper.Map<Microsoft.SharePoint.Client.ClientRuntimeContext>(context);
            string url_ = url;
            bool isEditLink_ = isEditLink;
            string expirationString_ = expirationString;
            var result__1044574026 = Microsoft.SharePoint.Client.Web.CreateAnonymousLinkWithExpiration(context_, url_, isEditLink_, expirationString_);
            return result__1044574026;
        }

        public void DeleteAllAnonymousLinksForObject(ProxyInterfaceSourceGeneratorTests.Source.PnP.IClientRuntimeContext context, string url)
        {
            Microsoft.SharePoint.Client.ClientRuntimeContext context_ = _mapper.Map<Microsoft.SharePoint.Client.ClientRuntimeContext>(context);
            string url_ = url;
            Microsoft.SharePoint.Client.Web.DeleteAllAnonymousLinksForObject(context_, url_);
        }

        public void DeleteAnonymousLinkForObject(ProxyInterfaceSourceGeneratorTests.Source.PnP.IClientRuntimeContext context, string url, bool isEditLink, bool removeAssociatedSharingLinkGroup)
        {
            Microsoft.SharePoint.Client.ClientRuntimeContext context_ = _mapper.Map<Microsoft.SharePoint.Client.ClientRuntimeContext>(context);
            string url_ = url;
            bool isEditLink_ = isEditLink;
            bool removeAssociatedSharingLinkGroup_ = removeAssociatedSharingLinkGroup;
            Microsoft.SharePoint.Client.Web.DeleteAnonymousLinkForObject(context_, url_, isEditLink_, removeAssociatedSharingLinkGroup_);
        }

        public Microsoft.SharePoint.Client.ListCollection GetLists(Microsoft.SharePoint.Client.GetListsParameters getListsParams)
        {
            Microsoft.SharePoint.Client.GetListsParameters getListsParams_ = getListsParams;
            var result_1293372807 = _Instance.GetLists(getListsParams_);
            return result_1293372807;
        }

        public Microsoft.SharePoint.Client.WebTemplateCollection GetAvailableWebTemplates(uint lcid, bool doIncludeCrossLanguage)
        {
            uint lcid_ = lcid;
            bool doIncludeCrossLanguage_ = doIncludeCrossLanguage;
            var result__1052443476 = _Instance.GetAvailableWebTemplates(lcid_, doIncludeCrossLanguage_);
            return result__1052443476;
        }

        public Microsoft.SharePoint.Client.List GetCatalog(int typeCatalog)
        {
            int typeCatalog_ = typeCatalog;
            var result__1458409307 = _Instance.GetCatalog(typeCatalog_);
            return result__1458409307;
        }

        public Microsoft.SharePoint.Client.RecycleBinItemCollection GetRecycleBinItems(string pagingInfo, int rowLimit, bool isAscending, Microsoft.SharePoint.Client.RecycleBinOrderBy orderBy, Microsoft.SharePoint.Client.RecycleBinItemState itemState)
        {
            string pagingInfo_ = pagingInfo;
            int rowLimit_ = rowLimit;
            bool isAscending_ = isAscending;
            Microsoft.SharePoint.Client.RecycleBinOrderBy orderBy_ = orderBy;
            Microsoft.SharePoint.Client.RecycleBinItemState itemState_ = itemState;
            var result_694026616 = _Instance.GetRecycleBinItems(pagingInfo_, rowLimit_, isAscending_, orderBy_, itemState_);
            return result_694026616;
        }

        public Microsoft.SharePoint.Client.RecycleBinItemCollection GetRecycleBinItemsByQueryInfo(Microsoft.SharePoint.Client.RecycleBinQueryInformation queryInfo)
        {
            Microsoft.SharePoint.Client.RecycleBinQueryInformation queryInfo_ = queryInfo;
            var result__1467955603 = _Instance.GetRecycleBinItemsByQueryInfo(queryInfo_);
            return result__1467955603;
        }

        public Microsoft.SharePoint.Client.ChangeCollection GetChanges(Microsoft.SharePoint.Client.ChangeQuery query)
        {
            Microsoft.SharePoint.Client.ChangeQuery query_ = query;
            var result_536201347 = _Instance.GetChanges(query_);
            return result_536201347;
        }

        public Microsoft.SharePoint.Client.List GetList(string strUrl)
        {
            string strUrl_ = strUrl;
            var result_1483657030 = _Instance.GetList(strUrl_);
            return result_1483657030;
        }

        public Microsoft.SharePoint.Client.List GetListUsingPath(Microsoft.SharePoint.Client.ResourcePath path)
        {
            Microsoft.SharePoint.Client.ResourcePath path_ = path;
            var result__2113955437 = _Instance.GetListUsingPath(path_);
            return result__2113955437;
        }

        public Microsoft.SharePoint.Client.ListItem GetListItem(string strUrl)
        {
            string strUrl_ = strUrl;
            var result_101515089 = _Instance.GetListItem(strUrl_);
            return result_101515089;
        }

        public Microsoft.SharePoint.Client.ListItem GetListItemUsingPath(Microsoft.SharePoint.Client.ResourcePath path)
        {
            Microsoft.SharePoint.Client.ResourcePath path_ = path;
            var result__577192176 = _Instance.GetListItemUsingPath(path_);
            return result__577192176;
        }

        public Microsoft.SharePoint.Client.ListItem GetListItemByResourceId(string resourceId)
        {
            string resourceId_ = resourceId;
            var result_569057021 = _Instance.GetListItemByResourceId(resourceId_);
            return result_569057021;
        }

        public Microsoft.BusinessData.MetadataModel.Entity GetEntity(string @namespace, string name)
        {
            string @namespace_ = @namespace;
            string name_ = name;
            var result_401289025 = _Instance.GetEntity(@namespace_, name_);
            return result_401289025;
        }

        public Microsoft.BusinessData.MetadataModel.AppBdcCatalog GetAppBdcCatalogForAppInstance(System.Guid appInstanceId)
        {
            System.Guid appInstanceId_ = appInstanceId;
            var result__1179378574 = _Instance.GetAppBdcCatalogForAppInstance(appInstanceId_);
            return result__1179378574;
        }

        public Microsoft.BusinessData.MetadataModel.AppBdcCatalog GetAppBdcCatalog()
        {
            var result__1128404427 = _Instance.GetAppBdcCatalog();
            return result__1128404427;
        }

        public Microsoft.SharePoint.Client.WebCollection GetSubwebsForCurrentUser(Microsoft.SharePoint.Client.SubwebQuery query)
        {
            Microsoft.SharePoint.Client.SubwebQuery query_ = query;
            var result__34039800 = _Instance.GetSubwebsForCurrentUser(query_);
            return result__34039800;
        }

        public Microsoft.SharePoint.Client.ClientResult<System.IO.Stream> GetSPAppContextAsStream()
        {
            var result_127789125 = _Instance.GetSPAppContextAsStream();
            return result_127789125;
        }

        public void Update()
        {
            _Instance.Update();
        }

        public Microsoft.SharePoint.Client.View GetViewFromUrl(string listUrl)
        {
            string listUrl_ = listUrl;
            var result_1074039380 = _Instance.GetViewFromUrl(listUrl_);
            return result_1074039380;
        }

        public Microsoft.SharePoint.Client.View GetViewFromPath(Microsoft.SharePoint.Client.ResourcePath listPath)
        {
            Microsoft.SharePoint.Client.ResourcePath listPath_ = listPath;
            var result_1126862484 = _Instance.GetViewFromPath(listPath_);
            return result_1126862484;
        }

        public Microsoft.SharePoint.Client.File GetFileByServerRelativeUrl(string serverRelativeUrl)
        {
            string serverRelativeUrl_ = serverRelativeUrl;
            var result__979182843 = _Instance.GetFileByServerRelativeUrl(serverRelativeUrl_);
            return result__979182843;
        }

        public Microsoft.SharePoint.Client.File GetFileByServerRelativePath(Microsoft.SharePoint.Client.ResourcePath serverRelativePath)
        {
            Microsoft.SharePoint.Client.ResourcePath serverRelativePath_ = serverRelativePath;
            var result_1456830503 = _Instance.GetFileByServerRelativePath(serverRelativePath_);
            return result_1456830503;
        }

        public System.Collections.Generic.IList<Microsoft.SharePoint.Client.DocumentLibraryInformation> GetDocumentLibraries(ProxyInterfaceSourceGeneratorTests.Source.PnP.IClientRuntimeContext context, string webFullUrl)
        {
            Microsoft.SharePoint.Client.ClientRuntimeContext context_ = _mapper.Map<Microsoft.SharePoint.Client.ClientRuntimeContext>(context);
            string webFullUrl_ = webFullUrl;
            var result_2078170246 = Microsoft.SharePoint.Client.Web.GetDocumentLibraries(context_, webFullUrl_);
            return result_2078170246;
        }

        public System.Collections.Generic.IList<Microsoft.SharePoint.Client.DocumentLibraryInformation> GetDocumentAndMediaLibraries(ProxyInterfaceSourceGeneratorTests.Source.PnP.IClientRuntimeContext context, string webFullUrl, bool includePageLibraries)
        {
            Microsoft.SharePoint.Client.ClientRuntimeContext context_ = _mapper.Map<Microsoft.SharePoint.Client.ClientRuntimeContext>(context);
            string webFullUrl_ = webFullUrl;
            bool includePageLibraries_ = includePageLibraries;
            var result__431075153 = Microsoft.SharePoint.Client.Web.GetDocumentAndMediaLibraries(context_, webFullUrl_, includePageLibraries_);
            return result__431075153;
        }

        public Microsoft.SharePoint.Client.ClientResult<Microsoft.SharePoint.Client.DocumentLibraryInformation> DefaultDocumentLibraryUrl(ProxyInterfaceSourceGeneratorTests.Source.PnP.IClientRuntimeContext context, string webUrl)
        {
            Microsoft.SharePoint.Client.ClientRuntimeContext context_ = _mapper.Map<Microsoft.SharePoint.Client.ClientRuntimeContext>(context);
            string webUrl_ = webUrl;
            var result_1125717726 = Microsoft.SharePoint.Client.Web.DefaultDocumentLibraryUrl(context_, webUrl_);
            return result_1125717726;
        }

        public Microsoft.SharePoint.Client.List DefaultDocumentLibrary()
        {
            var result_69743263 = _Instance.DefaultDocumentLibrary();
            return result_69743263;
        }

        public Microsoft.SharePoint.Client.File GetFileById(System.Guid uniqueId)
        {
            System.Guid uniqueId_ = uniqueId;
            var result__223228596 = _Instance.GetFileById(uniqueId_);
            return result__223228596;
        }

        public Microsoft.SharePoint.Client.Folder GetFolderById(System.Guid uniqueId)
        {
            System.Guid uniqueId_ = uniqueId;
            var result__2111623002 = _Instance.GetFolderById(uniqueId_);
            return result__2111623002;
        }

        public Microsoft.SharePoint.Client.File GetFileByLinkingUrl(string linkingUrl)
        {
            string linkingUrl_ = linkingUrl;
            var result__104450524 = _Instance.GetFileByLinkingUrl(linkingUrl_);
            return result__104450524;
        }

        public Microsoft.SharePoint.Client.File GetFileByGuestUrl(string guestUrl)
        {
            string guestUrl_ = guestUrl;
            var result_1819257688 = _Instance.GetFileByGuestUrl(guestUrl_);
            return result_1819257688;
        }

        public Microsoft.SharePoint.Client.File GetFileByGuestUrlEnsureAccess(string guestUrl, bool ensureAccess)
        {
            string guestUrl_ = guestUrl;
            bool ensureAccess_ = ensureAccess;
            var result__323239372 = _Instance.GetFileByGuestUrlEnsureAccess(guestUrl_, ensureAccess_);
            return result__323239372;
        }

        public Microsoft.SharePoint.Client.File GetFileByWOPIFrameUrl(string wopiFrameUrl)
        {
            string wopiFrameUrl_ = wopiFrameUrl;
            var result_1184208158 = _Instance.GetFileByWOPIFrameUrl(wopiFrameUrl_);
            return result_1184208158;
        }

        public Microsoft.SharePoint.Client.File GetFileByUrl(string fileUrl)
        {
            string fileUrl_ = fileUrl;
            var result__84028506 = _Instance.GetFileByUrl(fileUrl_);
            return result__84028506;
        }

        public Microsoft.SharePoint.Client.Folder GetFolderByServerRelativeUrl(string serverRelativeUrl)
        {
            string serverRelativeUrl_ = serverRelativeUrl;
            var result_1556909417 = _Instance.GetFolderByServerRelativeUrl(serverRelativeUrl_);
            return result_1556909417;
        }

        public Microsoft.SharePoint.Client.Folder GetFolderByServerRelativePath(Microsoft.SharePoint.Client.ResourcePath serverRelativePath)
        {
            Microsoft.SharePoint.Client.ResourcePath serverRelativePath_ = serverRelativePath;
            var result__1812606997 = _Instance.GetFolderByServerRelativePath(serverRelativePath_);
            return result__1812606997;
        }

        public void ApplyWebTemplate(string webTemplate)
        {
            string webTemplate_ = webTemplate;
            _Instance.ApplyWebTemplate(webTemplate_);
        }

        public void DeleteObject()
        {
            _Instance.DeleteObject();
        }

        public Microsoft.SharePoint.Client.ClientResult<System.IO.Stream> PageContextInfo(bool includeODBSettings, bool emitNavigationInfo)
        {
            bool includeODBSettings_ = includeODBSettings;
            bool emitNavigationInfo_ = emitNavigationInfo;
            var result_1488981072 = _Instance.PageContextInfo(includeODBSettings_, emitNavigationInfo_);
            return result_1488981072;
        }

        public Microsoft.SharePoint.Client.ClientResult<System.IO.Stream> PageContextCore()
        {
            var result_769613763 = _Instance.PageContextCore();
            return result_769613763;
        }

        public Microsoft.SharePoint.Client.AppInstance GetAppInstanceById(System.Guid appInstanceId)
        {
            System.Guid appInstanceId_ = appInstanceId;
            var result__860011802 = _Instance.GetAppInstanceById(appInstanceId_);
            return result__860011802;
        }

        public Microsoft.SharePoint.Client.ClientObjectList<Microsoft.SharePoint.Client.AppInstance> GetAppInstancesByProductId(System.Guid productId)
        {
            System.Guid productId_ = productId;
            var result__1349849408 = _Instance.GetAppInstancesByProductId(productId_);
            return result__1349849408;
        }

        public Microsoft.SharePoint.Client.AppInstance LoadAndInstallAppInSpecifiedLocale(System.IO.Stream appPackageStream, int installationLocaleLCID)
        {
            System.IO.Stream appPackageStream_ = appPackageStream;
            int installationLocaleLCID_ = installationLocaleLCID;
            var result__860277814 = _Instance.LoadAndInstallAppInSpecifiedLocale(appPackageStream_, installationLocaleLCID_);
            return result__860277814;
        }

        public Microsoft.SharePoint.Client.AppInstance LoadApp(System.IO.Stream appPackageStream, int installationLocaleLCID)
        {
            System.IO.Stream appPackageStream_ = appPackageStream;
            int installationLocaleLCID_ = installationLocaleLCID;
            var result__1043610289 = _Instance.LoadApp(appPackageStream_, installationLocaleLCID_);
            return result__1043610289;
        }

        public Microsoft.SharePoint.Client.ClientResult<System.Guid> AddPlaceholderUser(string listId, string placeholderText)
        {
            string listId_ = listId;
            string placeholderText_ = placeholderText;
            var result__256231457 = _Instance.AddPlaceholderUser(listId_, placeholderText_);
            return result__256231457;
        }

        public Microsoft.SharePoint.Client.AppInstance LoadAndInstallApp(System.IO.Stream appPackageStream)
        {
            System.IO.Stream appPackageStream_ = appPackageStream;
            var result__1506697459 = _Instance.LoadAndInstallApp(appPackageStream_);
            return result__1506697459;
        }

        public void SetAccessRequestSiteDescriptionAndUpdate(string description)
        {
            string description_ = description;
            _Instance.SetAccessRequestSiteDescriptionAndUpdate(description_);
        }

        public void SetUseAccessRequestDefaultAndUpdate(bool useAccessRequestDefault)
        {
            bool useAccessRequestDefault_ = useAccessRequestDefault;
            _Instance.SetUseAccessRequestDefaultAndUpdate(useAccessRequestDefault_);
        }

        public void IncrementSiteClientTag()
        {
            _Instance.IncrementSiteClientTag();
        }

        public void AddSupportedUILanguage(int lcid)
        {
            int lcid_ = lcid;
            _Instance.AddSupportedUILanguage(lcid_);
        }

        public void RemoveSupportedUILanguage(int lcid)
        {
            int lcid_ = lcid;
            _Instance.RemoveSupportedUILanguage(lcid_);
        }

        public Microsoft.SharePoint.Client.User EnsureUser(string logonName)
        {
            string logonName_ = logonName;
            var result_1853915411 = _Instance.EnsureUser(logonName_);
            return result_1853915411;
        }

        public Microsoft.SharePoint.Client.User EnsureUserByObjectId(System.Guid objectId, System.Guid tenantId, Microsoft.SharePoint.Client.Utilities.PrincipalType principalType)
        {
            System.Guid objectId_ = objectId;
            System.Guid tenantId_ = tenantId;
            Microsoft.SharePoint.Client.Utilities.PrincipalType principalType_ = principalType;
            var result__1490083264 = _Instance.EnsureUserByObjectId(objectId_, tenantId_, principalType_);
            return result__1490083264;
        }

        public void ApplyTheme(string colorPaletteUrl, string fontSchemeUrl, string backgroundImageUrl, bool shareGenerated)
        {
            string colorPaletteUrl_ = colorPaletteUrl;
            string fontSchemeUrl_ = fontSchemeUrl;
            string backgroundImageUrl_ = backgroundImageUrl;
            bool shareGenerated_ = shareGenerated;
            _Instance.ApplyTheme(colorPaletteUrl_, fontSchemeUrl_, backgroundImageUrl_, shareGenerated_);
        }





        public WebProxy(Microsoft.SharePoint.Client.Web instance) : base(instance)
        {
            _Instance = instance;
            _InstanceBase = instance;

            _mapper = new MapperConfiguration(cfg =>
            {
                cfg.CreateMap<Microsoft.SharePoint.Client.ClientRuntimeContext, ProxyInterfaceSourceGeneratorTests.Source.PnP.IClientRuntimeContext>().ConstructUsing(instance_205293328 => new ProxyInterfaceSourceGeneratorTests.Source.PnP.ClientRuntimeContextProxy(instance_205293328));
                cfg.CreateMap<ProxyInterfaceSourceGeneratorTests.Source.PnP.IClientRuntimeContext, Microsoft.SharePoint.Client.ClientRuntimeContext>().ConstructUsing(proxy1345472640 => ((ProxyInterfaceSourceGeneratorTests.Source.PnP.ClientRuntimeContextProxy) proxy1345472640)._Instance);
                cfg.CreateMap<Microsoft.SharePoint.Client.ClientObject, ProxyInterfaceSourceGeneratorTests.Source.PnP.IClientObject>().ConstructUsing(instance_895746668 => new ProxyInterfaceSourceGeneratorTests.Source.PnP.ClientObjectProxy(instance_895746668));
                cfg.CreateMap<ProxyInterfaceSourceGeneratorTests.Source.PnP.IClientObject, Microsoft.SharePoint.Client.ClientObject>().ConstructUsing(proxy1674261376 => ((ProxyInterfaceSourceGeneratorTests.Source.PnP.ClientObjectProxy) proxy1674261376)._Instance);
                cfg.CreateMap<Microsoft.SharePoint.Client.SecurableObject, ProxyInterfaceSourceGeneratorTests.Source.PnP.ISecurableObject>().ConstructUsing(instance592284880 => new ProxyInterfaceSourceGeneratorTests.Source.PnP.SecurableObjectProxy(instance592284880));
                cfg.CreateMap<ProxyInterfaceSourceGeneratorTests.Source.PnP.ISecurableObject, Microsoft.SharePoint.Client.SecurableObject>().ConstructUsing(proxy_300636294 => ((ProxyInterfaceSourceGeneratorTests.Source.PnP.SecurableObjectProxy) proxy_300636294)._Instance);
                cfg.CreateMap<Microsoft.SharePoint.Client.ClientContext, ProxyInterfaceSourceGeneratorTests.Source.PnP.IClientContext>().ConstructUsing(instance_1283184912 => new ProxyInterfaceSourceGeneratorTests.Source.PnP.ClientContextProxy(instance_1283184912));
                cfg.CreateMap<ProxyInterfaceSourceGeneratorTests.Source.PnP.IClientContext, Microsoft.SharePoint.Client.ClientContext>().ConstructUsing(proxy1267236400 => ((ProxyInterfaceSourceGeneratorTests.Source.PnP.ClientContextProxy) proxy1267236400)._Instance);
            }).CreateMapper();

        }

        private readonly IMapper _mapper;
    }
}
#nullable disable