//----------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by https://github.com/StefH/ProxyInterfaceSourceGenerator.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//----------------------------------------------------------------------------------------

#nullable enable
using System;


    public partial class NoNamespaceProxy : INoNamespace
    {
        public ProxyInterfaceSourceGeneratorTests.Source.NoNamespace _Instance { get; }
        

        public bool Test { get => _Instance.Test; set => _Instance.Test = value; }







        public NoNamespaceProxy(ProxyInterfaceSourceGeneratorTests.Source.NoNamespace instance)
        {
            _Instance = instance;
            


        }
    }

#nullable disable