//----------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by https://github.com/StefH/ProxyInterfaceSourceGenerator.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//----------------------------------------------------------------------------------------

#nullable enable
using System;
using AutoMapper;

namespace ProxyInterfaceSourceGeneratorTests.Source
{
    public class PersonProxy : IPerson
    {
        public ProxyInterfaceSourceGeneratorTests.Source.Person _Instance { get; }

        public string Name { get => _Instance.Name; set => _Instance.Name = value; }

        public string? StringNullable { get => _Instance.StringNullable; set => _Instance.StringNullable = value; }

        public long? NullableLong { get => _Instance.NullableLong; }

        public object @object { get => _Instance.@object; set => _Instance.@object = value; }



        public void Void()
        {
            _Instance.Void();
        }

        public string HelloWorld(string name)
        {
            string name_ = name;
            var result_62514245 = _Instance.HelloWorld(name_);
            return result_62514245;
        }

        public void WithParams(params string[] values)
        {
            string[] values_ = values;
            _Instance.WithParams(values_);
        }

        public string Add(string s, string @string)
        {
            string s_ = s;
            string @string_ = @string;
            var result_62514245 = _Instance.Add(s_, @string_);
            return result_62514245;
        }

        public int DefaultValue(int x = 100)
        {
            int x_ = x;
            var result_36894086 = _Instance.DefaultValue(x_);
            return result_36894086;
        }

        public void In_Out_Ref1(in int a, out int b, ref int c)
        {
            int a_ = a;
            int b_;
            int c_ = c;
            _Instance.In_Out_Ref1(in a_, out b_, ref c_);
            b = b_;
        }

        public bool Generic2<T1, T2>(int x, T1 t1, T2 t2) where T1 : struct where T2 : class, new()
        {
            int x_ = x;
            T1 t1_ = t1;
            T2 t2_ = t2;
            var result_49305352 = _Instance.Generic2<T1, T2>(x_, t1_, t2_);
            return result_49305352;
        }

        public System.Threading.Tasks.Task Method1Async()
        {
            var result_50731275 = _Instance.Method1Async();
            return result_50731275;
        }

        public System.Threading.Tasks.Task<int> Method2Async()
        {
            var result_1115207109 = _Instance.Method2Async();
            return result_1115207109;
        }

        public System.Threading.Tasks.Task<string?> Method3Async()
        {
            var result_1140827268 = _Instance.Method3Async();
            return result_1140827268;
        }





        public PersonProxy(ProxyInterfaceSourceGeneratorTests.Source.Person instance)
        {
            _Instance = instance;


        }


    }
}
#nullable disable