//----------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by https://github.com/StefH/ProxyInterfaceSourceGenerator.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//----------------------------------------------------------------------------------------

#nullable enable
using System;

namespace ProxyInterfaceSourceGeneratorTests.Source.PnP
{
    public partial interface IClientObject
    {
        ProxyInterfaceSourceGeneratorTests.Source.PnP.IClientRuntimeContext Context { get; }

        object Tag { get; set; }

        Microsoft.SharePoint.Client.ObjectPath Path { get; }

        string ObjectVersion { get; set; }

        bool? ServerObjectIsNull { get; }

        ProxyInterfaceSourceGeneratorTests.Source.PnP.IClientObject TypedObject { get; }



        void FromJson(Microsoft.SharePoint.Client.JsonReader reader);

        bool CustomFromJson(Microsoft.SharePoint.Client.JsonReader reader);

        void Retrieve();

        void Retrieve(params string[] propertyNames);

        void RefreshLoad();

        bool IsPropertyAvailable(string propertyName);

        bool IsObjectPropertyInstantiated(string propertyName);




    }
}
#nullable disable