//----------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by https://github.com/StefH/ProxyInterfaceSourceGenerator.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//----------------------------------------------------------------------------------------

#nullable enable
using System;

namespace ProxyInterfaceDemo
{
    public partial class GroupProxy : global::ProxyInterfaceDemo.DisplayableProxy, global::ProxyInterfaceDemo.IGroup
    {


        public new global::ProxyInterfaceDemo.Group _Instance { get; }
        public global::ProxyInterfaceDemo.Displayable _InstanceDisplayable { get; }

        public GroupProxy(global::ProxyInterfaceDemo.Group instance) : base(instance)
        {
            _Instance = instance;
            _InstanceDisplayable = instance;
        }
    }
}
#nullable restore