//----------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by https://github.com/StefH/ProxyInterfaceSourceGenerator.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//----------------------------------------------------------------------------------------

#nullable enable
using System;

namespace ProxyInterfaceSourceGeneratorTests.Source
{
    public partial class NoSetterOrGetterProxy : global::ProxyInterfaceSourceGeneratorTests.Source.INoSetterOrGetter
    {

        private static global::ProxyInterfaceSourceGeneratorTests.Source.IBar MapToInterface(global::ProxyInterfaceSourceGeneratorTests.Source.Bar value)
        {
            return new global::ProxyInterfaceSourceGeneratorTests.Source.BarProxy(value);
        }

        private static global::ProxyInterfaceSourceGeneratorTests.Source.Bar2 MapToInstance(global::ProxyInterfaceSourceGeneratorTests.Source.IBar2 value)
        {
            return value._Instance;
        }



        public global::ProxyInterfaceSourceGeneratorTests.Source.NoSetterOrGetter _Instance { get; }
        
        public global::ProxyInterfaceSourceGeneratorTests.Source.IBar? BarNoSetter { get => _Instance.BarNoSetter != null ? MapToInterface(_Instance.BarNoSetter) : null; }

        public global::ProxyInterfaceSourceGeneratorTests.Source.IBar2? Bar2NoPublicGetter { set => _Instance.Bar2NoPublicGetter = value != null ? MapToInstance(value) : null; }


        public NoSetterOrGetterProxy(global::ProxyInterfaceSourceGeneratorTests.Source.NoSetterOrGetter instance)
        {
            _Instance = instance;
            
        }
    }
}
#nullable restore