//----------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by https://github.com/StefH/ProxyInterfaceSourceGenerator.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//----------------------------------------------------------------------------------------

#nullable enable
using System;

namespace ProxyInterfaceSourceGeneratorTests.Source
{
    public partial class NoSetterProxy : global::ProxyInterfaceSourceGeneratorTests.Source.INoSetter
    {

        private static global::ProxyInterfaceSourceGeneratorTests.Source.IBar MapToInterface(global::ProxyInterfaceSourceGeneratorTests.Source.Bar value)
        {
            return new global::ProxyInterfaceSourceGeneratorTests.Source.BarProxy(value);
        }

        private static global::ProxyInterfaceSourceGeneratorTests.Source.Bar MapToInstance(global::ProxyInterfaceSourceGeneratorTests.Source.IBar value)
        {
            return value._Instance;
        }



        public global::ProxyInterfaceSourceGeneratorTests.Source.NoSetter _Instance { get; }
        
        public global::ProxyInterfaceSourceGeneratorTests.Source.IBar? Bar { get => _Instance.Bar != null ? MapToInterface(_Instance.Bar) : null; }


        public NoSetterProxy(global::ProxyInterfaceSourceGeneratorTests.Source.NoSetter instance)
        {
            _Instance = instance;
            
        }
    }
}
#nullable restore