//----------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by https://github.com/StefH/ProxyInterfaceSourceGenerator.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//----------------------------------------------------------------------------------------

#nullable enable
using System;

namespace ProxyInterfaceSourceGeneratorTests.Source.PnP
{
    public partial interface IClientObject
    {
        Microsoft.SharePoint.Client.ClientObject _Instance { get; }

        ProxyInterfaceSourceGeneratorTests.Source.PnP.IClientRuntimeContext Context { get; }

        object Tag { get; set; }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        Microsoft.SharePoint.Client.ObjectPath Path { get; }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        string ObjectVersion { get; set; }

        [Microsoft.SharePoint.Client.PseudoRemoteAttribute]
        bool? ServerObjectIsNull { get; }

        ProxyInterfaceSourceGeneratorTests.Source.PnP.IClientObject TypedObject { get; }



        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        void FromJson(Microsoft.SharePoint.Client.JsonReader reader);

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        bool CustomFromJson(Microsoft.SharePoint.Client.JsonReader reader);

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        void Retrieve();

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        void Retrieve(params string[] propertyNames);

        void RefreshLoad();

        bool IsPropertyAvailable(string propertyName);

        bool IsObjectPropertyInstantiated(string propertyName);




    }
}