//----------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by https://github.com/StefH/ProxyInterfaceSourceGenerator.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//----------------------------------------------------------------------------------------

#nullable enable
using System;

namespace ProxyInterfaceSourceGeneratorTests.Source
{
    public partial class ClassDirectAndIndirectProxy : global::ProxyInterfaceSourceGeneratorTests.Source.IClassDirectAndIndirect
    {
        static ClassDirectAndIndirectProxy()
        {
            Mapster.TypeAdapterConfig<global::ProxyInterfaceSourceGeneratorTests.Source.ClassDirectAndIndirect, global::ProxyInterfaceSourceGeneratorTests.Source.IClassDirectAndIndirect>.NewConfig().ConstructUsing(instance2067235185 => new global::ProxyInterfaceSourceGeneratorTests.Source.ClassDirectAndIndirectProxy(instance2067235185));
            Mapster.TypeAdapterConfig<global::ProxyInterfaceSourceGeneratorTests.Source.IClassDirectAndIndirect, global::ProxyInterfaceSourceGeneratorTests.Source.ClassDirectAndIndirect>.NewConfig().MapWith(proxy2067235185 => proxy2067235185._Instance);

        }

        private static global::ProxyInterfaceSourceGeneratorTests.Source.IClassDirectAndIndirect[] MapToInterface(global::ProxyInterfaceSourceGeneratorTests.Source.ClassDirectAndIndirect[] value)
        {
            return Mapster.TypeAdapter.Adapt<global::ProxyInterfaceSourceGeneratorTests.Source.IClassDirectAndIndirect[]>(value);
        }

        private static global::ProxyInterfaceSourceGeneratorTests.Source.ClassDirectAndIndirect[] MapToInstance(global::ProxyInterfaceSourceGeneratorTests.Source.IClassDirectAndIndirect[] value)
        {
            return Mapster.TypeAdapter.Adapt<global::ProxyInterfaceSourceGeneratorTests.Source.ClassDirectAndIndirect[]>(value);
        }

        private static global::System.Collections.Generic.List<global::ProxyInterfaceSourceGeneratorTests.Source.IClassDirectAndIndirect> MapToInterface(global::System.Collections.Generic.List<global::ProxyInterfaceSourceGeneratorTests.Source.ClassDirectAndIndirect> value)
        {
            return Mapster.TypeAdapter.Adapt<global::System.Collections.Generic.List<global::ProxyInterfaceSourceGeneratorTests.Source.IClassDirectAndIndirect>>(value);
        }

        private static global::System.Collections.Generic.List<global::ProxyInterfaceSourceGeneratorTests.Source.ClassDirectAndIndirect> MapToInstance(global::System.Collections.Generic.List<global::ProxyInterfaceSourceGeneratorTests.Source.IClassDirectAndIndirect> value)
        {
            return Mapster.TypeAdapter.Adapt<global::System.Collections.Generic.List<global::ProxyInterfaceSourceGeneratorTests.Source.ClassDirectAndIndirect>>(value);
        }

        private static global::ProxyInterfaceSourceGeneratorTests.Source.IClassDirectAndIndirect MapToInterface(global::ProxyInterfaceSourceGeneratorTests.Source.ClassDirectAndIndirect value)
        {
            return new global::ProxyInterfaceSourceGeneratorTests.Source.ClassDirectAndIndirectProxy(value);
        }

        private static global::ProxyInterfaceSourceGeneratorTests.Source.ClassDirectAndIndirect MapToInstance(global::ProxyInterfaceSourceGeneratorTests.Source.IClassDirectAndIndirect value)
        {
            return value._Instance;
        }



        public global::ProxyInterfaceSourceGeneratorTests.Source.ClassDirectAndIndirect _Instance { get; }
        
        public global::ProxyInterfaceSourceGeneratorTests.Source.IClassDirectAndIndirect? Value { get => _Instance.Value != null ? MapToInterface(_Instance.Value) : null; set => _Instance.Value = value != null ? MapToInstance(value) : null; }

        public global::ProxyInterfaceSourceGeneratorTests.Source.IClassDirectAndIndirect[] Array { get => MapToInterface(_Instance.Array); set => _Instance.Array = MapToInstance(value); }

        public global::System.Collections.Generic.List<global::ProxyInterfaceSourceGeneratorTests.Source.IClassDirectAndIndirect> List { get => MapToInterface(_Instance.List); set => _Instance.List = MapToInstance(value); }

        public int Test(global::ProxyInterfaceSourceGeneratorTests.Source.IClassDirectAndIndirect[] array, global::System.Collections.Generic.List<global::ProxyInterfaceSourceGeneratorTests.Source.IClassDirectAndIndirect> list, global::ProxyInterfaceSourceGeneratorTests.Source.IClassDirectAndIndirect value, global::ProxyInterfaceSourceGeneratorTests.Source.IClassDirectAndIndirect? valueNullable)
        {
            global::ProxyInterfaceSourceGeneratorTests.Source.ClassDirectAndIndirect[] array_ = MapToInstance(array);
            global::System.Collections.Generic.List<global::ProxyInterfaceSourceGeneratorTests.Source.ClassDirectAndIndirect> list_ = MapToInstance(list);
            global::ProxyInterfaceSourceGeneratorTests.Source.ClassDirectAndIndirect value_ = MapToInstance(value);
            global::ProxyInterfaceSourceGeneratorTests.Source.ClassDirectAndIndirect? valueNullable_ = valueNullable != null ? MapToInstance(valueNullable) : null;
            var result__1701808026 = _Instance.Test(array_, list_, value_, valueNullable_);
            return result__1701808026;
        }


        public ClassDirectAndIndirectProxy(global::ProxyInterfaceSourceGeneratorTests.Source.ClassDirectAndIndirect instance)
        {
            _Instance = instance;
            
        }
    }
}
#nullable restore