//----------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by https://github.com/StefH/ProxyInterfaceSourceGenerator.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//----------------------------------------------------------------------------------------

#nullable enable
using System;

namespace ProxyInterfaceSourceGeneratorTests.Source
{
    public partial class ClassRequiredPropertyProxy : global::ProxyInterfaceSourceGeneratorTests.Source.IClassRequiredProperty
    {


        public global::ProxyInterfaceSourceGeneratorTests.Source.ClassRequiredProperty _Instance { get; }
        
        public required string Test { get => _Instance.Test; set => _Instance.Test = value; }

        public required string Test2
        {
            get => _Instance.Test2;
            init => throw new NotImplementedException();
        }


        public ClassRequiredPropertyProxy(global::ProxyInterfaceSourceGeneratorTests.Source.ClassRequiredProperty instance)
        {
            _Instance = instance;
            
        }
    }
}
#nullable restore