//----------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by https://github.com/StefH/ProxyInterfaceSourceGenerator.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//----------------------------------------------------------------------------------------

#nullable enable
using System;

namespace ProxyInterfaceDemo
{
    public partial class DestroyableProxy : global::ProxyInterfaceDemo.IDestroyable
    {


        public global::ProxyInterfaceDemo.Destroyable _Instance { get; }
        

        public DestroyableProxy(global::ProxyInterfaceDemo.Destroyable instance)
        {
            _Instance = instance;
            
        }
    }
}
#nullable restore