//----------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by https://github.com/StefH/ProxyInterfaceSourceGenerator.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//----------------------------------------------------------------------------------------

#nullable enable
using System;

namespace ProxyInterfaceSourceGeneratorTests.Source
{
    public partial class ClassDirectProxy : global::ProxyInterfaceSourceGeneratorTests.Source.IClassDirect
    {

        private static global::ProxyInterfaceSourceGeneratorTests.Source.IClassDirect MapToInterface(global::ProxyInterfaceSourceGeneratorTests.Source.ClassDirect value)
        {
            return new global::ProxyInterfaceSourceGeneratorTests.Source.ClassDirectProxy(value);
        }

        private static global::ProxyInterfaceSourceGeneratorTests.Source.ClassDirect MapToInstance(global::ProxyInterfaceSourceGeneratorTests.Source.IClassDirect value)
        {
            return value._Instance;
        }



        public global::ProxyInterfaceSourceGeneratorTests.Source.ClassDirect _Instance { get; }
        
        public global::ProxyInterfaceSourceGeneratorTests.Source.IClassDirect Test(global::ProxyInterfaceSourceGeneratorTests.Source.IClassDirect x)
        {
            global::ProxyInterfaceSourceGeneratorTests.Source.ClassDirect x_ = MapToInstance(x);
            var result__1701808026 = _Instance.Test(x_);
            return MapToInterface(result__1701808026);
        }


        public ClassDirectProxy(global::ProxyInterfaceSourceGeneratorTests.Source.ClassDirect instance)
        {
            _Instance = instance;
            
        }
    }
}
#nullable restore