//----------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by https://github.com/StefH/ProxyInterfaceSourceGenerator.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//----------------------------------------------------------------------------------------

#nullable enable
using System;

namespace ProxyInterfaceSourceGeneratorTests.Source
{
    public partial interface IClassDirectAndIndirect
    {
        global::ProxyInterfaceSourceGeneratorTests.Source.ClassDirectAndIndirect _Instance { get; }

        global::ProxyInterfaceSourceGeneratorTests.Source.IClassDirectAndIndirect? Value { get; set; }

        global::ProxyInterfaceSourceGeneratorTests.Source.IClassDirectAndIndirect[] Array { get; set; }

        global::System.Collections.Generic.List<global::ProxyInterfaceSourceGeneratorTests.Source.IClassDirectAndIndirect> List { get; set; }

        int Test(global::ProxyInterfaceSourceGeneratorTests.Source.IClassDirectAndIndirect[] array, global::System.Collections.Generic.List<global::ProxyInterfaceSourceGeneratorTests.Source.IClassDirectAndIndirect> list, global::ProxyInterfaceSourceGeneratorTests.Source.IClassDirectAndIndirect value, global::ProxyInterfaceSourceGeneratorTests.Source.IClassDirectAndIndirect? valueNullable);
    }
}
#nullable restore