//----------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by https://github.com/StefH/ProxyInterfaceSourceGenerator.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//----------------------------------------------------------------------------------------

#nullable enable
using System;

namespace ProxyInterfaceSourceGeneratorTests.Namespace1
{
    public partial class ClassInNamespaceProxy : global::ProxyInterfaceSourceGeneratorTests.Namespace1.IClassInNamespace
    {


        public global::ProxyInterfaceSourceGeneratorTests.Namespace1.ClassInNamespace _Instance { get; }
        

        public ClassInNamespaceProxy(global::ProxyInterfaceSourceGeneratorTests.Namespace1.ClassInNamespace instance)
        {
            _Instance = instance;
            
        }
    }
}
#nullable restore