//----------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by https://github.com/StefH/ProxyInterfaceSourceGenerator.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//----------------------------------------------------------------------------------------

#nullable enable
using System;

namespace ProxyInterfaceSourceGeneratorTests.Source
{
    public partial class HumanProxy : IHuman
    {
        public ProxyInterfaceSourceGeneratorTests.Source.Human _Instance { get; }
        

        public bool IsAlive { get => _Instance.IsAlive; set => _Instance.IsAlive = value; }

        public string GetterOnly { get => _Instance.GetterOnly; }









        public HumanProxy(ProxyInterfaceSourceGeneratorTests.Source.Human instance)
        {
            _Instance = instance;
            


        }
    }
}
#nullable disable