//----------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by https://github.com/StefH/ProxyInterfaceSourceGenerator.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//----------------------------------------------------------------------------------------

#nullable enable
using System;

namespace ProxyInterfaceSourceGeneratorTests.Source
{
    public partial class PersonProxy : global::ProxyInterfaceSourceGeneratorTests.Source.HumanProxy, global::ProxyInterfaceSourceGeneratorTests.Source.IPerson
    {
        public new global::ProxyInterfaceSourceGeneratorTests.Source.Person _Instance { get; }
        public global::ProxyInterfaceSourceGeneratorTests.Source.Human _InstanceHuman { get; }
        public global::ProxyInterfaceSourceGeneratorTests.Source.IHuman? Human { get => _Instance.Human != null ? Mapster.TypeAdapter.Adapt<global::ProxyInterfaceSourceGeneratorTests.Source.IHuman?>(_Instance.Human) : null; set => _Instance.Human = value != null ? Mapster.TypeAdapter.Adapt<ProxyInterfaceSourceGeneratorTests.Source.Human?>(value) : null; }

        public global::System.Collections.Generic.List<global::ProxyInterfaceSourceGeneratorTests.Source.IHuman> Humans { get => Mapster.TypeAdapter.Adapt<global::System.Collections.Generic.List<global::ProxyInterfaceSourceGeneratorTests.Source.IHuman>>(_Instance.Humans); set => _Instance.Humans = Mapster.TypeAdapter.Adapt<System.Collections.Generic.List<ProxyInterfaceSourceGeneratorTests.Source.Human>>(value); }

        [System.ComponentModel.DataAnnotations.DisplayAttribute(Prompt = "MyStruct Indexer")]
        public global::ProxyInterfaceSourceGeneratorTests.Source.MyStruct this[int i] { get => _Instance[i]; set => _Instance[i] = value; }

        public global::ProxyInterfaceSourceGeneratorTests.Source.MyStruct this[int i, string s] { get => _Instance[i, s]; set => _Instance[i, s] = value; }

        [System.ComponentModel.DataAnnotations.DisplayAttribute(ResourceType = typeof(System.Threading.PeriodicTimer))]
        public string Name { get => _Instance.Name; set => _Instance.Name = value; }

        public string? StringNullable { get => _Instance.StringNullable; set => _Instance.StringNullable = value; }

        public long? NullableLong { get => _Instance.NullableLong; }

        public object @object { get => _Instance.@object; set => _Instance.@object = value; }

        public global::ProxyInterfaceSourceGeneratorTests.Source.IHuman? GetHuman(global::ProxyInterfaceSourceGeneratorTests.Source.IHuman? h1, global::ProxyInterfaceSourceGeneratorTests.Source.IHuman? h2, global::ProxyInterfaceSourceGeneratorTests.Source.IHuman h3)
        {
            global::ProxyInterfaceSourceGeneratorTests.Source.Human? h1_ = h1 != null ? Mapster.TypeAdapter.Adapt<global::ProxyInterfaceSourceGeneratorTests.Source.Human?>(h1) : null;
            global::ProxyInterfaceSourceGeneratorTests.Source.Human? h2_ = h2 != null ? Mapster.TypeAdapter.Adapt<global::ProxyInterfaceSourceGeneratorTests.Source.Human?>(h2) : null;
            global::ProxyInterfaceSourceGeneratorTests.Source.Human h3_ = Mapster.TypeAdapter.Adapt<global::ProxyInterfaceSourceGeneratorTests.Source.Human>(h3);
            var result_121857625 = _Instance.GetHuman(h1_, h2_, h3_);
            return Mapster.TypeAdapter.Adapt<global::ProxyInterfaceSourceGeneratorTests.Source.IHuman?>(result_121857625);
        }

        public global::System.Collections.Generic.IList<global::ProxyInterfaceSourceGeneratorTests.Source.IHuman> AddHuman(global::ProxyInterfaceSourceGeneratorTests.Source.IHuman h)
        {
            global::ProxyInterfaceSourceGeneratorTests.Source.Human h_ = Mapster.TypeAdapter.Adapt<global::ProxyInterfaceSourceGeneratorTests.Source.Human>(h);
            var result_907493286 = _Instance.AddHuman(h_);
            return Mapster.TypeAdapter.Adapt<global::System.Collections.Generic.IList<global::ProxyInterfaceSourceGeneratorTests.Source.IHuman>>(result_907493286);
        }

        public void Void()
        {
            _Instance.Void();
        }

        public string HelloWorld(string name)
        {
            string name_ = name;
            var result_282270798 = _Instance.HelloWorld(name_);
            return result_282270798;
        }

        public string HelloWorld2(string? name = "x")
        {
            string? name_ = name;
            var result__1104421408 = _Instance.HelloWorld2(name_);
            return result__1104421408;
        }

        public string HelloWorld3(char? ch = 'c')
        {
            char? ch_ = ch;
            var result__1104421409 = _Instance.HelloWorld3(ch_);
            return result__1104421409;
        }

        public string HelloWorld4(char ch)
        {
            char ch_ = ch;
            var result__1104421414 = _Instance.HelloWorld4(ch_);
            return result__1104421414;
        }

        public string HelloWorld5(char? ch)
        {
            char? ch_ = ch;
            var result__1104421415 = _Instance.HelloWorld5(ch_);
            return result__1104421415;
        }

        public void WithParams(params string[] values)
        {
            string[] values_ = values;
            _Instance.WithParams(values_);
        }

        public string Add(string s, string @string)
        {
            string s_ = s;
            string @string_ = @string;
            var result__1127157211 = _Instance.Add(s_, @string_);
            return result__1127157211;
        }

        public int DefaultValue(int x = 100)
        {
            int x_ = x;
            var result__378509684 = _Instance.DefaultValue(x_);
            return result__378509684;
        }

        public void In_Out_Ref1(in int a, out int b, ref int c)
        {
            int b_;
            _Instance.In_Out_Ref1(in a, out b_, ref c);
            b = b_;
        }

        public double[,] Out_MultiDimensionIssue54(out double[,] x)
        {
            double[,] x_;
            var result_692039870 = _Instance.Out_MultiDimensionIssue54(out x_);
            x = x_;
            return result_692039870;
        }

        public bool Generic2<T1, T2>(int x, T1 t1, T2 t2) where T1 : struct where T2 : class, new()
        {
            int x_ = x;
            T1 t1_ = t1;
            T2 t2_ = t2;
            var result_542538942 = _Instance.Generic2<T1, T2>(x_, t1_, t2_);
            return result_542538942;
        }

        public global::System.Threading.Tasks.Task Method1Async()
        {
            var result__57678382 = _Instance.Method1Async();
            return result__57678382;
        }

        public global::System.Threading.Tasks.Task<int> Method2Async()
        {
            var result__57677169 = _Instance.Method2Async();
            return result__57677169;
        }

        [System.ComponentModel.DataAnnotations.DisplayAttribute(Name = "M3")]
        public global::System.Threading.Tasks.Task<string?> Method3Async()
        {
            var result__57684656 = _Instance.Method3Async();
            return result__57684656;
        }

        public void CreateInvokeHttpClient(int i = 5, string? appId = null, global::System.Collections.Generic.IReadOnlyDictionary<string, string>? metadata = null, global::System.Threading.CancellationToken token = default(System.Threading.CancellationToken))
        {
            int i_ = i;
            string? appId_ = appId;
            global::System.Collections.Generic.IReadOnlyDictionary<string, string>? metadata_ = metadata;
            global::System.Threading.CancellationToken token_ = token;
            _Instance.CreateInvokeHttpClient(i_, appId_, metadata_, token_);
        }

        public bool TryParse(string s1, [System.Diagnostics.CodeAnalysis.NotNullWhenAttribute(true)] params int[]? ii)
        {
            string s1_ = s1;
            int[]? ii_ = ii;
            var result__1226565302 = _Instance.TryParse(s1_, ii_);
            return result__1226565302;
        }

        public bool TryParse(string s2, [System.Diagnostics.CodeAnalysis.NotNullWhenAttribute(true)] out int? i)
        {
            string s2_ = s2;
            int? i_;
            var result__1226565302 = _Instance.TryParse(s2_, out i_);
            i = i_;
            return result__1226565302;
        }


        public PersonProxy(global::ProxyInterfaceSourceGeneratorTests.Source.Person instance) : base(instance)
        {
            _Instance = instance;
            _InstanceHuman = instance;

            Mapster.TypeAdapterConfig<global::ProxyInterfaceSourceGeneratorTests.Source.Human, global::ProxyInterfaceSourceGeneratorTests.Source.IHuman>.NewConfig().ConstructUsing(instance2145588841 => new global::ProxyInterfaceSourceGeneratorTests.Source.HumanProxy(instance2145588841));
            Mapster.TypeAdapterConfig<global::ProxyInterfaceSourceGeneratorTests.Source.IHuman, global::ProxyInterfaceSourceGeneratorTests.Source.Human>.NewConfig().MapWith(proxy1567394325 => ((global::ProxyInterfaceSourceGeneratorTests.Source.HumanProxy) proxy1567394325)._Instance);


        }
    }
}
#nullable restore