//----------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by https://github.com/StefH/ProxyInterfaceSourceGenerator.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//----------------------------------------------------------------------------------------

#nullable enable
using System;

namespace ProxyInterfaceSourceGeneratorTests.Source
{
    public partial interface IClassRequiredProperty
    {
        global::ProxyInterfaceSourceGeneratorTests.Source.ClassRequiredProperty _Instance { get; }

        string Test { get; set; }


    }
}
#nullable restore