//----------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by https://github.com/StefH/ProxyInterfaceSourceGenerator.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//----------------------------------------------------------------------------------------

#nullable enable
using System;

namespace ProxyInterfaceDemo
{
    public partial class DisplayableProxy : global::ProxyInterfaceDemo.IDisplayable
    {


        public global::ProxyInterfaceDemo.Displayable _Instance { get; }
        

        public DisplayableProxy(global::ProxyInterfaceDemo.Displayable instance)
        {
            _Instance = instance;
            
        }
    }
}
#nullable restore