//----------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by https://github.com/StefH/ProxyInterfaceSourceGenerator.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//----------------------------------------------------------------------------------------

#nullable enable
using System;

namespace ProxyInterfaceSourceGeneratorTests.Source
{
    public partial interface IÜberGeneric<T1, TKey, KAi>
    {
        global::ProxyInterfaceSourceGeneratorTests.Source.ÜberGeneric<T1, TKey, KAi> _Instance { get; }

        T1 Test(T1 value);

        KAi Test(KAi value);

        TKey Test(TKey value);
    }
}
#nullable restore