//----------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by https://github.com/StefH/ProxyInterfaceSourceGenerator.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//----------------------------------------------------------------------------------------

#nullable enable
using System;

namespace ProxyInterfaceSourceGeneratorTests.Source
{
    public partial class BarProxy : global::ProxyInterfaceSourceGeneratorTests.Source.IBar
    {


        public global::ProxyInterfaceSourceGeneratorTests.Source.Bar _Instance { get; }
        

        public BarProxy(global::ProxyInterfaceSourceGeneratorTests.Source.Bar instance)
        {
            _Instance = instance;
            
        }
    }
}
#nullable restore