//----------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by https://github.com/StefH/ProxyInterfaceSourceGenerator.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//----------------------------------------------------------------------------------------

#nullable enable
using System;

namespace ProxyInterfaceSourceGeneratorTests.Source.PnP
{
    public partial interface IClientRuntimeContext : global::System.IDisposable
    {
        Microsoft.SharePoint.Client.ClientRuntimeContext _Instance { get; }

        string Url { get; }

        string ApplicationName { get; set; }

        string ClientTag { get; set; }

        bool DisableReturnValueCache { get; set; }

        bool ValidateOnClient { get; set; }

        System.Net.ICredentials Credentials { get; set; }

        Microsoft.SharePoint.Client.WebRequestExecutorFactory WebRequestExecutorFactory { get; set; }

        Microsoft.SharePoint.Client.ClientRequest PendingRequest { get; }

        bool HasPendingRequest { get; }

        object Tag { get; set; }

        int RequestTimeout { get; set; }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        System.Collections.Generic.Dictionary<string, object> StaticObjects { get; }

        System.Version ServerSchemaVersion { get; }

        System.Version ServerLibraryVersion { get; }

        System.Version RequestSchemaVersion { get; set; }

        string TraceCorrelationId { get; set; }



        void ExecuteQuery();

        void RetryQuery(Microsoft.SharePoint.Client.ClientRequest request);

        System.Threading.Tasks.Task ExecuteQueryAsync();

        System.Threading.Tasks.Task RetryQueryAsync(Microsoft.SharePoint.Client.ClientRequest request);

        T CastTo<T>(ProxyInterfaceSourceGeneratorTests.Source.PnP.IClientObject obj) where T : Microsoft.SharePoint.Client.ClientObject;

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        void AddQuery(Microsoft.SharePoint.Client.ClientAction query);

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        void AddQueryIdAndResultObject(long id, object obj);

        object ParseObjectFromJsonString(string json);

        void AddClientTypeAssembly(System.Reflection.Assembly @assembly);

        void Load<T>(T clientObject, params System.Linq.Expressions.Expression<System.Func<T, object>>[] retrievals) where T : Microsoft.SharePoint.Client.ClientObject;

        System.Collections.Generic.IEnumerable<T> LoadQuery<T>(Microsoft.SharePoint.Client.ClientObjectCollection<T> clientObjects) where T : Microsoft.SharePoint.Client.ClientObject;

        System.Collections.Generic.IEnumerable<T> LoadQuery<T>(System.Linq.IQueryable<T> clientObjects) where T : Microsoft.SharePoint.Client.ClientObject;



        event System.EventHandler<Microsoft.SharePoint.Client.WebRequestEventArgs> ExecutingWebRequest;


    }
}
#nullable restore