//----------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by https://github.com/StefH/ProxyInterfaceSourceGenerator.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//----------------------------------------------------------------------------------------

#nullable enable
using System;

namespace ProxyInterfaceSourceGeneratorTests.Source
{
    public partial class OperatorTestProxy : IOperatorTest
    {
        public ProxyInterfaceSourceGeneratorTests.Source.OperatorTest _Instance { get; }
        

        public string Name { get => _Instance.Name; set => _Instance.Name = value; }







       public static implicit operator OperatorTestProxy(string name)
       {
           var op_Implicit_ = name;
           return (OperatorTestProxy) op_Implicit_;
       }

       public static explicit operator string(OperatorTestProxy test)
       {
           var op_Explicit_ = Mapster.TypeAdapter.Adapt<OperatorTest>(test);
           return (string) op_Explicit_;
       }



        public OperatorTestProxy(ProxyInterfaceSourceGeneratorTests.Source.OperatorTest instance)
        {
            _Instance = instance;
            


        }
    }
}
#nullable disable