//----------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by https://github.com/StefH/ProxyInterfaceSourceGenerator.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//----------------------------------------------------------------------------------------

#nullable enable
using System;

namespace ProxyInterfaceSourceGeneratorTests.Source
{
    public partial class Bar2Proxy : global::ProxyInterfaceSourceGeneratorTests.Source.IBar2
    {


        public global::ProxyInterfaceSourceGeneratorTests.Source.Bar2 _Instance { get; }
        

        public Bar2Proxy(global::ProxyInterfaceSourceGeneratorTests.Source.Bar2 instance)
        {
            _Instance = instance;
            
        }
    }
}
#nullable restore