//----------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by https://github.com/StefH/ProxyInterfaceSourceGenerator.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//----------------------------------------------------------------------------------------

#nullable enable
using System;

namespace ProxyInterfaceSourceGeneratorTests.Source
{
    internal partial class TestClassInternalProxy : ITestClassInternal
    {
        public ProxyInterfaceSourceGeneratorTests.Source.TestClassInternal _Instance { get; }
        

        public bool Test { get => _Instance.Test; set => _Instance.Test = value; }









        public TestClassInternalProxy(ProxyInterfaceSourceGeneratorTests.Source.TestClassInternal instance)
        {
            _Instance = instance;
            


        }
    }
}
#nullable disable