//----------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by https://github.com/StefH/ProxyInterfaceSourceGenerator.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//----------------------------------------------------------------------------------------

#nullable enable
using System;

namespace ProxyInterfaceSourceGeneratorTests.Source
{
    public partial class HttpMessageInvokerProxy : IHttpMessageInvoker
    {
        public System.Net.Http.HttpMessageInvoker _Instance { get; }
        



        [System.Runtime.Versioning.UnsupportedOSPlatformAttribute("browser")]
        public virtual System.Net.Http.HttpResponseMessage Send(System.Net.Http.HttpRequestMessage request, System.Threading.CancellationToken cancellationToken)
        {
            System.Net.Http.HttpRequestMessage request_ = request;
            System.Threading.CancellationToken cancellationToken_ = cancellationToken;
            var result__989347188 = _Instance.Send(request_, cancellationToken_);
            return result__989347188;
        }

        public virtual System.Threading.Tasks.Task<System.Net.Http.HttpResponseMessage> SendAsync(System.Net.Http.HttpRequestMessage request, System.Threading.CancellationToken cancellationToken)
        {
            System.Net.Http.HttpRequestMessage request_ = request;
            System.Threading.CancellationToken cancellationToken_ = cancellationToken;
            var result__1161702976 = _Instance.SendAsync(request_, cancellationToken_);
            return result__1161702976;
        }

        public void Dispose()
        {
            _Instance.Dispose();
        }







        public HttpMessageInvokerProxy(System.Net.Http.HttpMessageInvoker instance)
        {
            _Instance = instance;
            


        }
    }
}
#nullable restore