//----------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by https://github.com/StefH/ProxyInterfaceSourceGenerator.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//----------------------------------------------------------------------------------------

#nullable enable
using System;

namespace ProxyInterfaceSourceGeneratorTests.Source.AzureSearch
{
    public partial class SearchIndexClientProxy : global::ProxyInterfaceSourceGeneratorTests.Source.AzureSearch.IAzureSearchIndexClient
    {


        public global::Azure.Search.Documents.Indexes.SearchIndexClient _Instance { get; }
        
        public virtual global::Azure.Core.Pipeline.HttpPipeline Pipeline { get => _Instance.Pipeline; }

        public virtual global::System.Uri Endpoint { get => _Instance.Endpoint; }

        public virtual string ServiceName { get => _Instance.ServiceName; }

        public virtual global::Azure.Response DeleteSynonymMap(string synonymMapName, global::Azure.MatchConditions matchConditions, global::Azure.RequestContext context)
        {
            string synonymMapName_ = synonymMapName;
            global::Azure.MatchConditions matchConditions_ = matchConditions;
            global::Azure.RequestContext context_ = context;
            var result_391338208 = _Instance.DeleteSynonymMap(synonymMapName_, matchConditions_, context_);
            return result_391338208;
        }

        public virtual global::System.Threading.Tasks.Task<global::Azure.Response> DeleteSynonymMapAsync(string synonymMapName, global::Azure.MatchConditions matchConditions, global::Azure.RequestContext context)
        {
            string synonymMapName_ = synonymMapName;
            global::Azure.MatchConditions matchConditions_ = matchConditions;
            global::Azure.RequestContext context_ = context;
            var result__1264012664 = _Instance.DeleteSynonymMapAsync(synonymMapName_, matchConditions_, context_);
            return result__1264012664;
        }

        public virtual global::Azure.Response DeleteSynonymMap(string synonymMapName, global::Azure.MatchConditions matchConditions = null!, global::System.Threading.CancellationToken cancellationToken = default)
        {
            string synonymMapName_ = synonymMapName;
            global::Azure.MatchConditions matchConditions_ = matchConditions;
            global::System.Threading.CancellationToken cancellationToken_ = cancellationToken;
            var result_391338208 = _Instance.DeleteSynonymMap(synonymMapName_, matchConditions_, cancellationToken_);
            return result_391338208;
        }

        public virtual global::System.Threading.Tasks.Task<global::Azure.Response> DeleteSynonymMapAsync(string synonymMapName, global::Azure.MatchConditions matchConditions = null!, global::System.Threading.CancellationToken cancellationToken = default)
        {
            string synonymMapName_ = synonymMapName;
            global::Azure.MatchConditions matchConditions_ = matchConditions;
            global::System.Threading.CancellationToken cancellationToken_ = cancellationToken;
            var result__1264012664 = _Instance.DeleteSynonymMapAsync(synonymMapName_, matchConditions_, cancellationToken_);
            return result__1264012664;
        }

        public virtual global::Azure.Response GetSynonymMap(string synonymMapName, global::Azure.RequestContext context)
        {
            string synonymMapName_ = synonymMapName;
            global::Azure.RequestContext context_ = context;
            var result__2104928417 = _Instance.GetSynonymMap(synonymMapName_, context_);
            return result__2104928417;
        }

        public virtual global::System.Threading.Tasks.Task<global::Azure.Response> GetSynonymMapAsync(string synonymMapName, global::Azure.RequestContext context)
        {
            string synonymMapName_ = synonymMapName;
            global::Azure.RequestContext context_ = context;
            var result__1953952275 = _Instance.GetSynonymMapAsync(synonymMapName_, context_);
            return result__1953952275;
        }

        public virtual global::Azure.Response<global::Azure.Search.Documents.Indexes.Models.SynonymMap> GetSynonymMap(string synonymMapName, global::System.Threading.CancellationToken cancellationToken = default)
        {
            string synonymMapName_ = synonymMapName;
            global::System.Threading.CancellationToken cancellationToken_ = cancellationToken;
            var result__2104928417 = _Instance.GetSynonymMap(synonymMapName_, cancellationToken_);
            return result__2104928417;
        }

        public virtual global::System.Threading.Tasks.Task<global::Azure.Response<global::Azure.Search.Documents.Indexes.Models.SynonymMap>> GetSynonymMapAsync(string synonymMapName, global::System.Threading.CancellationToken cancellationToken = default)
        {
            string synonymMapName_ = synonymMapName;
            global::System.Threading.CancellationToken cancellationToken_ = cancellationToken;
            var result__1953952275 = _Instance.GetSynonymMapAsync(synonymMapName_, cancellationToken_);
            return result__1953952275;
        }

        public virtual global::Azure.Response CreateSynonymMap(global::Azure.Core.RequestContent content, global::Azure.RequestContext context = null!)
        {
            global::Azure.Core.RequestContent content_ = content;
            global::Azure.RequestContext context_ = context;
            var result__1940466003 = _Instance.CreateSynonymMap(content_, context_);
            return result__1940466003;
        }

        public virtual global::System.Threading.Tasks.Task<global::Azure.Response> CreateSynonymMapAsync(global::Azure.Core.RequestContent content, global::Azure.RequestContext context = null!)
        {
            global::Azure.Core.RequestContent content_ = content;
            global::Azure.RequestContext context_ = context;
            var result_809442335 = _Instance.CreateSynonymMapAsync(content_, context_);
            return result_809442335;
        }

        public virtual global::Azure.Response<global::Azure.Search.Documents.Indexes.Models.SynonymMap> CreateSynonymMap(global::Azure.Search.Documents.Indexes.Models.SynonymMap synonymMap, global::System.Threading.CancellationToken cancellationToken = default)
        {
            global::Azure.Search.Documents.Indexes.Models.SynonymMap synonymMap_ = synonymMap;
            global::System.Threading.CancellationToken cancellationToken_ = cancellationToken;
            var result__1940466003 = _Instance.CreateSynonymMap(synonymMap_, cancellationToken_);
            return result__1940466003;
        }

        public virtual global::System.Threading.Tasks.Task<global::Azure.Response<global::Azure.Search.Documents.Indexes.Models.SynonymMap>> CreateSynonymMapAsync(global::Azure.Search.Documents.Indexes.Models.SynonymMap synonymMap, global::System.Threading.CancellationToken cancellationToken = default)
        {
            global::Azure.Search.Documents.Indexes.Models.SynonymMap synonymMap_ = synonymMap;
            global::System.Threading.CancellationToken cancellationToken_ = cancellationToken;
            var result_809442335 = _Instance.CreateSynonymMapAsync(synonymMap_, cancellationToken_);
            return result_809442335;
        }

        public virtual global::Azure.Response DeleteIndex(string indexName, global::Azure.MatchConditions matchConditions, global::Azure.RequestContext context)
        {
            string indexName_ = indexName;
            global::Azure.MatchConditions matchConditions_ = matchConditions;
            global::Azure.RequestContext context_ = context;
            var result__1905380477 = _Instance.DeleteIndex(indexName_, matchConditions_, context_);
            return result__1905380477;
        }

        public virtual global::System.Threading.Tasks.Task<global::Azure.Response> DeleteIndexAsync(string indexName, global::Azure.MatchConditions matchConditions, global::Azure.RequestContext context)
        {
            string indexName_ = indexName;
            global::Azure.MatchConditions matchConditions_ = matchConditions;
            global::Azure.RequestContext context_ = context;
            var result_344127265 = _Instance.DeleteIndexAsync(indexName_, matchConditions_, context_);
            return result_344127265;
        }

        public virtual global::Azure.Response DeleteIndex(string indexName, global::Azure.MatchConditions matchConditions = null!, global::System.Threading.CancellationToken cancellationToken = default)
        {
            string indexName_ = indexName;
            global::Azure.MatchConditions matchConditions_ = matchConditions;
            global::System.Threading.CancellationToken cancellationToken_ = cancellationToken;
            var result__1905380477 = _Instance.DeleteIndex(indexName_, matchConditions_, cancellationToken_);
            return result__1905380477;
        }

        public virtual global::System.Threading.Tasks.Task<global::Azure.Response> DeleteIndexAsync(string indexName, global::Azure.MatchConditions matchConditions = null!, global::System.Threading.CancellationToken cancellationToken = default)
        {
            string indexName_ = indexName;
            global::Azure.MatchConditions matchConditions_ = matchConditions;
            global::System.Threading.CancellationToken cancellationToken_ = cancellationToken;
            var result_344127265 = _Instance.DeleteIndexAsync(indexName_, matchConditions_, cancellationToken_);
            return result_344127265;
        }

        public virtual global::Azure.Response GetIndex(string indexName, global::Azure.RequestContext context)
        {
            string indexName_ = indexName;
            global::Azure.RequestContext context_ = context;
            var result__174279834 = _Instance.GetIndex(indexName_, context_);
            return result__174279834;
        }

        public virtual global::System.Threading.Tasks.Task<global::Azure.Response> GetIndexAsync(string indexName, global::Azure.RequestContext context)
        {
            string indexName_ = indexName;
            global::Azure.RequestContext context_ = context;
            var result__192683442 = _Instance.GetIndexAsync(indexName_, context_);
            return result__192683442;
        }

        public virtual global::Azure.Response<global::Azure.Search.Documents.Indexes.Models.SearchIndex> GetIndex(string indexName, global::System.Threading.CancellationToken cancellationToken = default)
        {
            string indexName_ = indexName;
            global::System.Threading.CancellationToken cancellationToken_ = cancellationToken;
            var result__174279834 = _Instance.GetIndex(indexName_, cancellationToken_);
            return result__174279834;
        }

        public virtual global::System.Threading.Tasks.Task<global::Azure.Response<global::Azure.Search.Documents.Indexes.Models.SearchIndex>> GetIndexAsync(string indexName, global::System.Threading.CancellationToken cancellationToken = default)
        {
            string indexName_ = indexName;
            global::System.Threading.CancellationToken cancellationToken_ = cancellationToken;
            var result__192683442 = _Instance.GetIndexAsync(indexName_, cancellationToken_);
            return result__192683442;
        }

        public virtual global::Azure.Pageable<global::System.BinaryData> GetIndexes(global::Azure.RequestContext context)
        {
            global::Azure.RequestContext context_ = context;
            var result__602643978 = _Instance.GetIndexes(context_);
            return result__602643978;
        }

        public virtual global::Azure.AsyncPageable<global::System.BinaryData> GetIndexesAsync(global::Azure.RequestContext context)
        {
            global::Azure.RequestContext context_ = context;
            var result_597064618 = _Instance.GetIndexesAsync(context_);
            return result_597064618;
        }

        public virtual global::Azure.Pageable<global::System.BinaryData> GetIndexesWithSelectedProperties(global::System.Collections.Generic.IEnumerable<string> @select, global::Azure.RequestContext context)
        {
            global::System.Collections.Generic.IEnumerable<string> @select_ = @select;
            global::Azure.RequestContext context_ = context;
            var result_1889121882 = _Instance.GetIndexesWithSelectedProperties(@select_, context_);
            return result_1889121882;
        }

        public virtual global::Azure.AsyncPageable<global::System.BinaryData> GetIndexesWithSelectedPropertiesAsync(global::System.Collections.Generic.IEnumerable<string> @select, global::Azure.RequestContext context)
        {
            global::System.Collections.Generic.IEnumerable<string> @select_ = @select;
            global::Azure.RequestContext context_ = context;
            var result__1660496494 = _Instance.GetIndexesWithSelectedPropertiesAsync(@select_, context_);
            return result__1660496494;
        }

        public virtual global::Azure.Pageable<global::Azure.Search.Documents.Indexes.Models.SearchIndexResponse> GetIndexesWithSelectedProperties(global::System.Collections.Generic.IEnumerable<string> @select = null!, global::System.Threading.CancellationToken cancellationToken = default)
        {
            global::System.Collections.Generic.IEnumerable<string> @select_ = @select;
            global::System.Threading.CancellationToken cancellationToken_ = cancellationToken;
            var result_1889121882 = _Instance.GetIndexesWithSelectedProperties(@select_, cancellationToken_);
            return result_1889121882;
        }

        public virtual global::Azure.AsyncPageable<global::Azure.Search.Documents.Indexes.Models.SearchIndexResponse> GetIndexesWithSelectedPropertiesAsync(global::System.Collections.Generic.IEnumerable<string> @select = null!, global::System.Threading.CancellationToken cancellationToken = default)
        {
            global::System.Collections.Generic.IEnumerable<string> @select_ = @select;
            global::System.Threading.CancellationToken cancellationToken_ = cancellationToken;
            var result__1660496494 = _Instance.GetIndexesWithSelectedPropertiesAsync(@select_, cancellationToken_);
            return result__1660496494;
        }

        public virtual global::Azure.Response CreateIndex(global::Azure.Core.RequestContent content, global::Azure.RequestContext context = null!)
        {
            global::Azure.Core.RequestContent content_ = content;
            global::Azure.RequestContext context_ = context;
            var result_428341114 = _Instance.CreateIndex(content_, context_);
            return result_428341114;
        }

        public virtual global::System.Threading.Tasks.Task<global::Azure.Response> CreateIndexAsync(global::Azure.Core.RequestContent content, global::Azure.RequestContext context = null!)
        {
            global::Azure.Core.RequestContent content_ = content;
            global::Azure.RequestContext context_ = context;
            var result__826180018 = _Instance.CreateIndexAsync(content_, context_);
            return result__826180018;
        }

        public virtual global::Azure.Response<global::Azure.Search.Documents.Indexes.Models.SearchIndex> CreateIndex(global::Azure.Search.Documents.Indexes.Models.SearchIndex index, global::System.Threading.CancellationToken cancellationToken = default)
        {
            global::Azure.Search.Documents.Indexes.Models.SearchIndex index_ = index;
            global::System.Threading.CancellationToken cancellationToken_ = cancellationToken;
            var result_428341114 = _Instance.CreateIndex(index_, cancellationToken_);
            return result_428341114;
        }

        public virtual global::System.Threading.Tasks.Task<global::Azure.Response<global::Azure.Search.Documents.Indexes.Models.SearchIndex>> CreateIndexAsync(global::Azure.Search.Documents.Indexes.Models.SearchIndex index, global::System.Threading.CancellationToken cancellationToken = default)
        {
            global::Azure.Search.Documents.Indexes.Models.SearchIndex index_ = index;
            global::System.Threading.CancellationToken cancellationToken_ = cancellationToken;
            var result__826180018 = _Instance.CreateIndexAsync(index_, cancellationToken_);
            return result__826180018;
        }

        public virtual global::Azure.Response GetIndexStatistics(string indexName, global::Azure.RequestContext context)
        {
            string indexName_ = indexName;
            global::Azure.RequestContext context_ = context;
            var result__1003915523 = _Instance.GetIndexStatistics(indexName_, context_);
            return result__1003915523;
        }

        public virtual global::System.Threading.Tasks.Task<global::Azure.Response> GetIndexStatisticsAsync(string indexName, global::Azure.RequestContext context)
        {
            string indexName_ = indexName;
            global::Azure.RequestContext context_ = context;
            var result_351551535 = _Instance.GetIndexStatisticsAsync(indexName_, context_);
            return result_351551535;
        }

        public virtual global::Azure.Response<global::Azure.Search.Documents.Indexes.Models.SearchIndexStatistics> GetIndexStatistics(string indexName, global::System.Threading.CancellationToken cancellationToken = default)
        {
            string indexName_ = indexName;
            global::System.Threading.CancellationToken cancellationToken_ = cancellationToken;
            var result__1003915523 = _Instance.GetIndexStatistics(indexName_, cancellationToken_);
            return result__1003915523;
        }

        public virtual global::System.Threading.Tasks.Task<global::Azure.Response<global::Azure.Search.Documents.Indexes.Models.SearchIndexStatistics>> GetIndexStatisticsAsync(string indexName, global::System.Threading.CancellationToken cancellationToken = default)
        {
            string indexName_ = indexName;
            global::System.Threading.CancellationToken cancellationToken_ = cancellationToken;
            var result_351551535 = _Instance.GetIndexStatisticsAsync(indexName_, cancellationToken_);
            return result_351551535;
        }

        public virtual global::Azure.Response AnalyzeText(string indexName, global::Azure.Core.RequestContent content, global::Azure.RequestContext context = null!)
        {
            string indexName_ = indexName;
            global::Azure.Core.RequestContent content_ = content;
            global::Azure.RequestContext context_ = context;
            var result_1701057949 = _Instance.AnalyzeText(indexName_, content_, context_);
            return result_1701057949;
        }

        public virtual global::System.Threading.Tasks.Task<global::Azure.Response> AnalyzeTextAsync(string indexName, global::Azure.Core.RequestContent content, global::Azure.RequestContext context = null!)
        {
            string indexName_ = indexName;
            global::Azure.Core.RequestContent content_ = content;
            global::Azure.RequestContext context_ = context;
            var result_402725703 = _Instance.AnalyzeTextAsync(indexName_, content_, context_);
            return result_402725703;
        }

        public virtual global::Azure.Response DeleteAlias(string aliasName, global::Azure.MatchConditions matchConditions, global::Azure.RequestContext context)
        {
            string aliasName_ = aliasName;
            global::Azure.MatchConditions matchConditions_ = matchConditions;
            global::Azure.RequestContext context_ = context;
            var result_1186389731 = _Instance.DeleteAlias(aliasName_, matchConditions_, context_);
            return result_1186389731;
        }

        public virtual global::System.Threading.Tasks.Task<global::Azure.Response> DeleteAliasAsync(string aliasName, global::Azure.MatchConditions matchConditions, global::Azure.RequestContext context)
        {
            string aliasName_ = aliasName;
            global::Azure.MatchConditions matchConditions_ = matchConditions;
            global::Azure.RequestContext context_ = context;
            var result_1055970029 = _Instance.DeleteAliasAsync(aliasName_, matchConditions_, context_);
            return result_1055970029;
        }

        public virtual global::Azure.Response DeleteAlias(string aliasName, global::Azure.MatchConditions matchConditions = null!, global::System.Threading.CancellationToken cancellationToken = default)
        {
            string aliasName_ = aliasName;
            global::Azure.MatchConditions matchConditions_ = matchConditions;
            global::System.Threading.CancellationToken cancellationToken_ = cancellationToken;
            var result_1186389731 = _Instance.DeleteAlias(aliasName_, matchConditions_, cancellationToken_);
            return result_1186389731;
        }

        public virtual global::System.Threading.Tasks.Task<global::Azure.Response> DeleteAliasAsync(string aliasName, global::Azure.MatchConditions matchConditions = null!, global::System.Threading.CancellationToken cancellationToken = default)
        {
            string aliasName_ = aliasName;
            global::Azure.MatchConditions matchConditions_ = matchConditions;
            global::System.Threading.CancellationToken cancellationToken_ = cancellationToken;
            var result_1055970029 = _Instance.DeleteAliasAsync(aliasName_, matchConditions_, cancellationToken_);
            return result_1055970029;
        }

        public virtual global::Azure.Response GetAlias(string aliasName, global::Azure.RequestContext context)
        {
            string aliasName_ = aliasName;
            global::Azure.RequestContext context_ = context;
            var result__1165775454 = _Instance.GetAlias(aliasName_, context_);
            return result__1165775454;
        }

        public virtual global::System.Threading.Tasks.Task<global::Azure.Response> GetAliasAsync(string aliasName, global::Azure.RequestContext context)
        {
            string aliasName_ = aliasName;
            global::Azure.RequestContext context_ = context;
            var result_277011358 = _Instance.GetAliasAsync(aliasName_, context_);
            return result_277011358;
        }

        public virtual global::Azure.Response<global::Azure.Search.Documents.Indexes.Models.SearchAlias> GetAlias(string aliasName, global::System.Threading.CancellationToken cancellationToken = default)
        {
            string aliasName_ = aliasName;
            global::System.Threading.CancellationToken cancellationToken_ = cancellationToken;
            var result__1165775454 = _Instance.GetAlias(aliasName_, cancellationToken_);
            return result__1165775454;
        }

        public virtual global::System.Threading.Tasks.Task<global::Azure.Response<global::Azure.Search.Documents.Indexes.Models.SearchAlias>> GetAliasAsync(string aliasName, global::System.Threading.CancellationToken cancellationToken = default)
        {
            string aliasName_ = aliasName;
            global::System.Threading.CancellationToken cancellationToken_ = cancellationToken;
            var result_277011358 = _Instance.GetAliasAsync(aliasName_, cancellationToken_);
            return result_277011358;
        }

        public virtual global::Azure.Pageable<global::System.BinaryData> GetAliases(global::Azure.RequestContext context)
        {
            global::Azure.RequestContext context_ = context;
            var result_513494886 = _Instance.GetAliases(context_);
            return result_513494886;
        }

        public virtual global::Azure.AsyncPageable<global::System.BinaryData> GetAliasesAsync(global::Azure.RequestContext context)
        {
            global::Azure.RequestContext context_ = context;
            var result__1606832466 = _Instance.GetAliasesAsync(context_);
            return result__1606832466;
        }

        public virtual global::Azure.Pageable<global::Azure.Search.Documents.Indexes.Models.SearchAlias> GetAliases(global::System.Threading.CancellationToken cancellationToken = default)
        {
            global::System.Threading.CancellationToken cancellationToken_ = cancellationToken;
            var result_513494886 = _Instance.GetAliases(cancellationToken_);
            return result_513494886;
        }

        public virtual global::Azure.AsyncPageable<global::Azure.Search.Documents.Indexes.Models.SearchAlias> GetAliasesAsync(global::System.Threading.CancellationToken cancellationToken = default)
        {
            global::System.Threading.CancellationToken cancellationToken_ = cancellationToken;
            var result__1606832466 = _Instance.GetAliasesAsync(cancellationToken_);
            return result__1606832466;
        }

        public virtual global::Azure.Response CreateAlias(global::Azure.Core.RequestContent content, global::Azure.RequestContext context = null!)
        {
            global::Azure.Core.RequestContent content_ = content;
            global::Azure.RequestContext context_ = context;
            var result_1275307778 = _Instance.CreateAlias(content_, context_);
            return result_1275307778;
        }

        public virtual global::System.Threading.Tasks.Task<global::Azure.Response> CreateAliasAsync(global::Azure.Core.RequestContent content, global::Azure.RequestContext context = null!)
        {
            global::Azure.Core.RequestContent content_ = content;
            global::Azure.RequestContext context_ = context;
            var result__91034518 = _Instance.CreateAliasAsync(content_, context_);
            return result__91034518;
        }

        public virtual global::Azure.Response<global::Azure.Search.Documents.Indexes.Models.SearchAlias> CreateAlias(global::Azure.Search.Documents.Indexes.Models.SearchAlias @alias, global::System.Threading.CancellationToken cancellationToken = default)
        {
            global::Azure.Search.Documents.Indexes.Models.SearchAlias @alias_ = @alias;
            global::System.Threading.CancellationToken cancellationToken_ = cancellationToken;
            var result_1275307778 = _Instance.CreateAlias(@alias_, cancellationToken_);
            return result_1275307778;
        }

        public virtual global::System.Threading.Tasks.Task<global::Azure.Response<global::Azure.Search.Documents.Indexes.Models.SearchAlias>> CreateAliasAsync(global::Azure.Search.Documents.Indexes.Models.SearchAlias @alias, global::System.Threading.CancellationToken cancellationToken = default)
        {
            global::Azure.Search.Documents.Indexes.Models.SearchAlias @alias_ = @alias;
            global::System.Threading.CancellationToken cancellationToken_ = cancellationToken;
            var result__91034518 = _Instance.CreateAliasAsync(@alias_, cancellationToken_);
            return result__91034518;
        }

        public virtual global::Azure.Response DeleteKnowledgeBase(string knowledgeBaseName, global::Azure.MatchConditions matchConditions, global::Azure.RequestContext context)
        {
            string knowledgeBaseName_ = knowledgeBaseName;
            global::Azure.MatchConditions matchConditions_ = matchConditions;
            global::Azure.RequestContext context_ = context;
            var result_1873838950 = _Instance.DeleteKnowledgeBase(knowledgeBaseName_, matchConditions_, context_);
            return result_1873838950;
        }

        public virtual global::System.Threading.Tasks.Task<global::Azure.Response> DeleteKnowledgeBaseAsync(string knowledgeBaseName, global::Azure.MatchConditions matchConditions, global::Azure.RequestContext context)
        {
            string knowledgeBaseName_ = knowledgeBaseName;
            global::Azure.MatchConditions matchConditions_ = matchConditions;
            global::Azure.RequestContext context_ = context;
            var result_1653894238 = _Instance.DeleteKnowledgeBaseAsync(knowledgeBaseName_, matchConditions_, context_);
            return result_1653894238;
        }

        public virtual global::Azure.Response DeleteKnowledgeBase(string knowledgeBaseName, global::Azure.MatchConditions matchConditions = null!, global::System.Threading.CancellationToken cancellationToken = default)
        {
            string knowledgeBaseName_ = knowledgeBaseName;
            global::Azure.MatchConditions matchConditions_ = matchConditions;
            global::System.Threading.CancellationToken cancellationToken_ = cancellationToken;
            var result_1873838950 = _Instance.DeleteKnowledgeBase(knowledgeBaseName_, matchConditions_, cancellationToken_);
            return result_1873838950;
        }

        public virtual global::System.Threading.Tasks.Task<global::Azure.Response> DeleteKnowledgeBaseAsync(string knowledgeBaseName, global::Azure.MatchConditions matchConditions = null!, global::System.Threading.CancellationToken cancellationToken = default)
        {
            string knowledgeBaseName_ = knowledgeBaseName;
            global::Azure.MatchConditions matchConditions_ = matchConditions;
            global::System.Threading.CancellationToken cancellationToken_ = cancellationToken;
            var result_1653894238 = _Instance.DeleteKnowledgeBaseAsync(knowledgeBaseName_, matchConditions_, cancellationToken_);
            return result_1653894238;
        }

        public virtual global::Azure.Response GetKnowledgeBase(string knowledgeBaseName, global::Azure.RequestContext context)
        {
            string knowledgeBaseName_ = knowledgeBaseName;
            global::Azure.RequestContext context_ = context;
            var result__2095664707 = _Instance.GetKnowledgeBase(knowledgeBaseName_, context_);
            return result__2095664707;
        }

        public virtual global::System.Threading.Tasks.Task<global::Azure.Response> GetKnowledgeBaseAsync(string knowledgeBaseName, global::Azure.RequestContext context)
        {
            string knowledgeBaseName_ = knowledgeBaseName;
            global::Azure.RequestContext context_ = context;
            var result__689320681 = _Instance.GetKnowledgeBaseAsync(knowledgeBaseName_, context_);
            return result__689320681;
        }

        public virtual global::Azure.Response<global::Azure.Search.Documents.Indexes.Models.KnowledgeBase> GetKnowledgeBase(string knowledgeBaseName, global::System.Threading.CancellationToken cancellationToken = default)
        {
            string knowledgeBaseName_ = knowledgeBaseName;
            global::System.Threading.CancellationToken cancellationToken_ = cancellationToken;
            var result__2095664707 = _Instance.GetKnowledgeBase(knowledgeBaseName_, cancellationToken_);
            return result__2095664707;
        }

        public virtual global::System.Threading.Tasks.Task<global::Azure.Response<global::Azure.Search.Documents.Indexes.Models.KnowledgeBase>> GetKnowledgeBaseAsync(string knowledgeBaseName, global::System.Threading.CancellationToken cancellationToken = default)
        {
            string knowledgeBaseName_ = knowledgeBaseName;
            global::System.Threading.CancellationToken cancellationToken_ = cancellationToken;
            var result__689320681 = _Instance.GetKnowledgeBaseAsync(knowledgeBaseName_, cancellationToken_);
            return result__689320681;
        }

        public virtual global::Azure.Pageable<global::System.BinaryData> GetKnowledgeBases(global::Azure.RequestContext context)
        {
            global::Azure.RequestContext context_ = context;
            var result__1454021232 = _Instance.GetKnowledgeBases(context_);
            return result__1454021232;
        }

        public virtual global::Azure.AsyncPageable<global::System.BinaryData> GetKnowledgeBasesAsync(global::Azure.RequestContext context)
        {
            global::Azure.RequestContext context_ = context;
            var result__1781927360 = _Instance.GetKnowledgeBasesAsync(context_);
            return result__1781927360;
        }

        public virtual global::Azure.Pageable<global::Azure.Search.Documents.Indexes.Models.KnowledgeBase> GetKnowledgeBases(global::System.Threading.CancellationToken cancellationToken = default)
        {
            global::System.Threading.CancellationToken cancellationToken_ = cancellationToken;
            var result__1454021232 = _Instance.GetKnowledgeBases(cancellationToken_);
            return result__1454021232;
        }

        public virtual global::Azure.AsyncPageable<global::Azure.Search.Documents.Indexes.Models.KnowledgeBase> GetKnowledgeBasesAsync(global::System.Threading.CancellationToken cancellationToken = default)
        {
            global::System.Threading.CancellationToken cancellationToken_ = cancellationToken;
            var result__1781927360 = _Instance.GetKnowledgeBasesAsync(cancellationToken_);
            return result__1781927360;
        }

        public virtual global::Azure.Response CreateKnowledgeBase(global::Azure.Core.RequestContent content, global::Azure.RequestContext context = null!)
        {
            global::Azure.Core.RequestContent content_ = content;
            global::Azure.RequestContext context_ = context;
            var result_191818039 = _Instance.CreateKnowledgeBase(content_, context_);
            return result_191818039;
        }

        public virtual global::System.Threading.Tasks.Task<global::Azure.Response> CreateKnowledgeBaseAsync(global::Azure.Core.RequestContent content, global::Azure.RequestContext context = null!)
        {
            global::Azure.Core.RequestContent content_ = content;
            global::Azure.RequestContext context_ = context;
            var result__1868928399 = _Instance.CreateKnowledgeBaseAsync(content_, context_);
            return result__1868928399;
        }

        public virtual global::Azure.Response DeleteKnowledgeSource(string sourceName, global::Azure.MatchConditions matchConditions, global::Azure.RequestContext context)
        {
            string sourceName_ = sourceName;
            global::Azure.MatchConditions matchConditions_ = matchConditions;
            global::Azure.RequestContext context_ = context;
            var result__1693336290 = _Instance.DeleteKnowledgeSource(sourceName_, matchConditions_, context_);
            return result__1693336290;
        }

        public virtual global::System.Threading.Tasks.Task<global::Azure.Response> DeleteKnowledgeSourceAsync(string sourceName, global::Azure.MatchConditions matchConditions, global::Azure.RequestContext context)
        {
            string sourceName_ = sourceName;
            global::Azure.MatchConditions matchConditions_ = matchConditions;
            global::Azure.RequestContext context_ = context;
            var result__676719858 = _Instance.DeleteKnowledgeSourceAsync(sourceName_, matchConditions_, context_);
            return result__676719858;
        }

        public virtual global::Azure.Response DeleteKnowledgeSource(string sourceName, global::Azure.MatchConditions matchConditions = null!, global::System.Threading.CancellationToken cancellationToken = default)
        {
            string sourceName_ = sourceName;
            global::Azure.MatchConditions matchConditions_ = matchConditions;
            global::System.Threading.CancellationToken cancellationToken_ = cancellationToken;
            var result__1693336290 = _Instance.DeleteKnowledgeSource(sourceName_, matchConditions_, cancellationToken_);
            return result__1693336290;
        }

        public virtual global::System.Threading.Tasks.Task<global::Azure.Response> DeleteKnowledgeSourceAsync(string sourceName, global::Azure.MatchConditions matchConditions = null!, global::System.Threading.CancellationToken cancellationToken = default)
        {
            string sourceName_ = sourceName;
            global::Azure.MatchConditions matchConditions_ = matchConditions;
            global::System.Threading.CancellationToken cancellationToken_ = cancellationToken;
            var result__676719858 = _Instance.DeleteKnowledgeSourceAsync(sourceName_, matchConditions_, cancellationToken_);
            return result__676719858;
        }

        public virtual global::Azure.Response GetKnowledgeSource(string sourceName, global::Azure.RequestContext context)
        {
            string sourceName_ = sourceName;
            global::Azure.RequestContext context_ = context;
            var result_2016798781 = _Instance.GetKnowledgeSource(sourceName_, context_);
            return result_2016798781;
        }

        public virtual global::System.Threading.Tasks.Task<global::Azure.Response> GetKnowledgeSourceAsync(string sourceName, global::Azure.RequestContext context)
        {
            string sourceName_ = sourceName;
            global::Azure.RequestContext context_ = context;
            var result_1650027663 = _Instance.GetKnowledgeSourceAsync(sourceName_, context_);
            return result_1650027663;
        }

        public virtual global::Azure.Response<global::Azure.Search.Documents.Indexes.Models.KnowledgeSource> GetKnowledgeSource(string sourceName, global::System.Threading.CancellationToken cancellationToken = default)
        {
            string sourceName_ = sourceName;
            global::System.Threading.CancellationToken cancellationToken_ = cancellationToken;
            var result_2016798781 = _Instance.GetKnowledgeSource(sourceName_, cancellationToken_);
            return result_2016798781;
        }

        public virtual global::System.Threading.Tasks.Task<global::Azure.Response<global::Azure.Search.Documents.Indexes.Models.KnowledgeSource>> GetKnowledgeSourceAsync(string sourceName, global::System.Threading.CancellationToken cancellationToken = default)
        {
            string sourceName_ = sourceName;
            global::System.Threading.CancellationToken cancellationToken_ = cancellationToken;
            var result_1650027663 = _Instance.GetKnowledgeSourceAsync(sourceName_, cancellationToken_);
            return result_1650027663;
        }

        public virtual global::Azure.Pageable<global::System.BinaryData> GetKnowledgeSources(global::Azure.RequestContext context)
        {
            global::Azure.RequestContext context_ = context;
            var result_1716753648 = _Instance.GetKnowledgeSources(context_);
            return result_1716753648;
        }

        public virtual global::Azure.AsyncPageable<global::System.BinaryData> GetKnowledgeSourcesAsync(global::Azure.RequestContext context)
        {
            global::Azure.RequestContext context_ = context;
            var result__756421064 = _Instance.GetKnowledgeSourcesAsync(context_);
            return result__756421064;
        }

        public virtual global::Azure.Pageable<global::Azure.Search.Documents.Indexes.Models.KnowledgeSource> GetKnowledgeSources(global::System.Threading.CancellationToken cancellationToken = default)
        {
            global::System.Threading.CancellationToken cancellationToken_ = cancellationToken;
            var result_1716753648 = _Instance.GetKnowledgeSources(cancellationToken_);
            return result_1716753648;
        }

        public virtual global::Azure.AsyncPageable<global::Azure.Search.Documents.Indexes.Models.KnowledgeSource> GetKnowledgeSourcesAsync(global::System.Threading.CancellationToken cancellationToken = default)
        {
            global::System.Threading.CancellationToken cancellationToken_ = cancellationToken;
            var result__756421064 = _Instance.GetKnowledgeSourcesAsync(cancellationToken_);
            return result__756421064;
        }

        public virtual global::Azure.Response CreateKnowledgeSource(global::Azure.Core.RequestContent content, global::Azure.RequestContext context = null!)
        {
            global::Azure.Core.RequestContent content_ = content;
            global::Azure.RequestContext context_ = context;
            var result__2025136409 = _Instance.CreateKnowledgeSource(content_, context_);
            return result__2025136409;
        }

        public virtual global::System.Threading.Tasks.Task<global::Azure.Response> CreateKnowledgeSourceAsync(global::Azure.Core.RequestContent content, global::Azure.RequestContext context = null!)
        {
            global::Azure.Core.RequestContent content_ = content;
            global::Azure.RequestContext context_ = context;
            var result_2108037481 = _Instance.CreateKnowledgeSourceAsync(content_, context_);
            return result_2108037481;
        }

        public virtual global::Azure.Response GetKnowledgeSourceStatus(string sourceName, global::Azure.RequestContext context)
        {
            string sourceName_ = sourceName;
            global::Azure.RequestContext context_ = context;
            var result__2099645511 = _Instance.GetKnowledgeSourceStatus(sourceName_, context_);
            return result__2099645511;
        }

        public virtual global::System.Threading.Tasks.Task<global::Azure.Response> GetKnowledgeSourceStatusAsync(string sourceName, global::Azure.RequestContext context)
        {
            string sourceName_ = sourceName;
            global::Azure.RequestContext context_ = context;
            var result_855542735 = _Instance.GetKnowledgeSourceStatusAsync(sourceName_, context_);
            return result_855542735;
        }

        public virtual global::Azure.Response<global::Azure.Search.Documents.KnowledgeBases.Models.KnowledgeSourceStatus> GetKnowledgeSourceStatus(string sourceName, global::System.Threading.CancellationToken cancellationToken = default)
        {
            string sourceName_ = sourceName;
            global::System.Threading.CancellationToken cancellationToken_ = cancellationToken;
            var result__2099645511 = _Instance.GetKnowledgeSourceStatus(sourceName_, cancellationToken_);
            return result__2099645511;
        }

        public virtual global::System.Threading.Tasks.Task<global::Azure.Response<global::Azure.Search.Documents.KnowledgeBases.Models.KnowledgeSourceStatus>> GetKnowledgeSourceStatusAsync(string sourceName, global::System.Threading.CancellationToken cancellationToken = default)
        {
            string sourceName_ = sourceName;
            global::System.Threading.CancellationToken cancellationToken_ = cancellationToken;
            var result_855542735 = _Instance.GetKnowledgeSourceStatusAsync(sourceName_, cancellationToken_);
            return result_855542735;
        }

        public virtual global::Azure.Response GetServiceStatistics(global::Azure.RequestContext context)
        {
            global::Azure.RequestContext context_ = context;
            var result_922800734 = _Instance.GetServiceStatistics(context_);
            return result_922800734;
        }

        public virtual global::System.Threading.Tasks.Task<global::Azure.Response> GetServiceStatisticsAsync(global::Azure.RequestContext context)
        {
            global::Azure.RequestContext context_ = context;
            var result_2047420782 = _Instance.GetServiceStatisticsAsync(context_);
            return result_2047420782;
        }

        public virtual global::Azure.Response<global::Azure.Search.Documents.Indexes.Models.SearchServiceStatistics> GetServiceStatistics(global::System.Threading.CancellationToken cancellationToken = default)
        {
            global::System.Threading.CancellationToken cancellationToken_ = cancellationToken;
            var result_922800734 = _Instance.GetServiceStatistics(cancellationToken_);
            return result_922800734;
        }

        public virtual global::System.Threading.Tasks.Task<global::Azure.Response<global::Azure.Search.Documents.Indexes.Models.SearchServiceStatistics>> GetServiceStatisticsAsync(global::System.Threading.CancellationToken cancellationToken = default)
        {
            global::System.Threading.CancellationToken cancellationToken_ = cancellationToken;
            var result_2047420782 = _Instance.GetServiceStatisticsAsync(cancellationToken_);
            return result_2047420782;
        }

        public virtual global::Azure.Response<global::Azure.Search.Documents.Indexes.Models.SearchAlias> CreateOrUpdateAlias(global::Azure.Search.Documents.Indexes.Models.SearchAlias @alias, bool onlyIfUnchanged = false, global::System.Threading.CancellationToken cancellationToken = default)
        {
            global::Azure.Search.Documents.Indexes.Models.SearchAlias @alias_ = @alias;
            bool onlyIfUnchanged_ = onlyIfUnchanged;
            global::System.Threading.CancellationToken cancellationToken_ = cancellationToken;
            var result_1178978846 = _Instance.CreateOrUpdateAlias(@alias_, onlyIfUnchanged_, cancellationToken_);
            return result_1178978846;
        }

        public virtual global::System.Threading.Tasks.Task<global::Azure.Response<global::Azure.Search.Documents.Indexes.Models.SearchAlias>> CreateOrUpdateAliasAsync(global::Azure.Search.Documents.Indexes.Models.SearchAlias @alias, bool onlyIfUnchanged = false, global::System.Threading.CancellationToken cancellationToken = default)
        {
            global::Azure.Search.Documents.Indexes.Models.SearchAlias @alias_ = @alias;
            bool onlyIfUnchanged_ = onlyIfUnchanged;
            global::System.Threading.CancellationToken cancellationToken_ = cancellationToken;
            var result__203857046 = _Instance.CreateOrUpdateAliasAsync(@alias_, onlyIfUnchanged_, cancellationToken_);
            return result__203857046;
        }

        public virtual global::Azure.Response DeleteAlias(global::Azure.Search.Documents.Indexes.Models.SearchAlias @alias, bool onlyIfUnchanged = false, global::System.Threading.CancellationToken cancellationToken = default)
        {
            global::Azure.Search.Documents.Indexes.Models.SearchAlias @alias_ = @alias;
            bool onlyIfUnchanged_ = onlyIfUnchanged;
            global::System.Threading.CancellationToken cancellationToken_ = cancellationToken;
            var result_1186389731 = _Instance.DeleteAlias(@alias_, onlyIfUnchanged_, cancellationToken_);
            return result_1186389731;
        }

        public virtual global::System.Threading.Tasks.Task<global::Azure.Response> DeleteAliasAsync(global::Azure.Search.Documents.Indexes.Models.SearchAlias @alias, bool onlyIfUnchanged = false, global::System.Threading.CancellationToken cancellationToken = default)
        {
            global::Azure.Search.Documents.Indexes.Models.SearchAlias @alias_ = @alias;
            bool onlyIfUnchanged_ = onlyIfUnchanged;
            global::System.Threading.CancellationToken cancellationToken_ = cancellationToken;
            var result_1055970029 = _Instance.DeleteAliasAsync(@alias_, onlyIfUnchanged_, cancellationToken_);
            return result_1055970029;
        }

        public virtual global::Azure.Search.Documents.SearchClient GetSearchClient(string indexName)
        {
            string indexName_ = indexName;
            var result__1451305091 = _Instance.GetSearchClient(indexName_);
            return result__1451305091;
        }

        public virtual global::Azure.Response<global::Azure.Search.Documents.Indexes.Models.SearchIndex> CreateOrUpdateIndex(global::Azure.Search.Documents.Indexes.Models.SearchIndex index, bool allowIndexDowntime = false, bool onlyIfUnchanged = false, global::System.Threading.CancellationToken cancellationToken = default)
        {
            global::Azure.Search.Documents.Indexes.Models.SearchIndex index_ = index;
            bool allowIndexDowntime_ = allowIndexDowntime;
            bool onlyIfUnchanged_ = onlyIfUnchanged;
            global::System.Threading.CancellationToken cancellationToken_ = cancellationToken;
            var result_540414686 = _Instance.CreateOrUpdateIndex(index_, allowIndexDowntime_, onlyIfUnchanged_, cancellationToken_);
            return result_540414686;
        }

        public virtual global::System.Threading.Tasks.Task<global::Azure.Response<global::Azure.Search.Documents.Indexes.Models.SearchIndex>> CreateOrUpdateIndexAsync(global::Azure.Search.Documents.Indexes.Models.SearchIndex index, bool allowIndexDowntime = false, bool onlyIfUnchanged = false, global::System.Threading.CancellationToken cancellationToken = default)
        {
            global::Azure.Search.Documents.Indexes.Models.SearchIndex index_ = index;
            bool allowIndexDowntime_ = allowIndexDowntime;
            bool onlyIfUnchanged_ = onlyIfUnchanged;
            global::System.Threading.CancellationToken cancellationToken_ = cancellationToken;
            var result_1469450446 = _Instance.CreateOrUpdateIndexAsync(index_, allowIndexDowntime_, onlyIfUnchanged_, cancellationToken_);
            return result_1469450446;
        }

        public virtual global::Azure.Response DeleteIndex(string indexName, global::System.Threading.CancellationToken cancellationToken = default)
        {
            string indexName_ = indexName;
            global::System.Threading.CancellationToken cancellationToken_ = cancellationToken;
            var result__1905380477 = _Instance.DeleteIndex(indexName_, cancellationToken_);
            return result__1905380477;
        }

        public virtual global::System.Threading.Tasks.Task<global::Azure.Response> DeleteIndexAsync(string indexName, global::System.Threading.CancellationToken cancellationToken = default)
        {
            string indexName_ = indexName;
            global::System.Threading.CancellationToken cancellationToken_ = cancellationToken;
            var result_344127265 = _Instance.DeleteIndexAsync(indexName_, cancellationToken_);
            return result_344127265;
        }

        public virtual global::Azure.Response DeleteIndex(global::Azure.Search.Documents.Indexes.Models.SearchIndex index, bool onlyIfUnchanged = false, global::System.Threading.CancellationToken cancellationToken = default)
        {
            global::Azure.Search.Documents.Indexes.Models.SearchIndex index_ = index;
            bool onlyIfUnchanged_ = onlyIfUnchanged;
            global::System.Threading.CancellationToken cancellationToken_ = cancellationToken;
            var result__1905380477 = _Instance.DeleteIndex(index_, onlyIfUnchanged_, cancellationToken_);
            return result__1905380477;
        }

        public virtual global::System.Threading.Tasks.Task<global::Azure.Response> DeleteIndexAsync(global::Azure.Search.Documents.Indexes.Models.SearchIndex index, bool onlyIfUnchanged = false, global::System.Threading.CancellationToken cancellationToken = default)
        {
            global::Azure.Search.Documents.Indexes.Models.SearchIndex index_ = index;
            bool onlyIfUnchanged_ = onlyIfUnchanged;
            global::System.Threading.CancellationToken cancellationToken_ = cancellationToken;
            var result_344127265 = _Instance.DeleteIndexAsync(index_, onlyIfUnchanged_, cancellationToken_);
            return result_344127265;
        }

        public virtual global::Azure.Pageable<string> GetIndexNames(global::System.Threading.CancellationToken cancellationToken = default)
        {
            global::System.Threading.CancellationToken cancellationToken_ = cancellationToken;
            var result__347149086 = _Instance.GetIndexNames(cancellationToken_);
            return result__347149086;
        }

        public virtual global::Azure.AsyncPageable<string> GetIndexNamesAsync(global::System.Threading.CancellationToken cancellationToken = default)
        {
            global::System.Threading.CancellationToken cancellationToken_ = cancellationToken;
            var result__1144606782 = _Instance.GetIndexNamesAsync(cancellationToken_);
            return result__1144606782;
        }

        public virtual global::Azure.Pageable<global::Azure.Search.Documents.Indexes.Models.SearchIndex> GetIndexes(global::System.Threading.CancellationToken cancellationToken = default)
        {
            global::System.Threading.CancellationToken cancellationToken_ = cancellationToken;
            var result__602643978 = _Instance.GetIndexes(cancellationToken_);
            return result__602643978;
        }

        public virtual global::Azure.AsyncPageable<global::Azure.Search.Documents.Indexes.Models.SearchIndex> GetIndexesAsync(global::System.Threading.CancellationToken cancellationToken = default)
        {
            global::System.Threading.CancellationToken cancellationToken_ = cancellationToken;
            var result_597064618 = _Instance.GetIndexesAsync(cancellationToken_);
            return result_597064618;
        }

        public virtual global::Azure.Response<global::Azure.Search.Documents.Indexes.Models.SynonymMap> CreateOrUpdateSynonymMap(global::Azure.Search.Documents.Indexes.Models.SynonymMap synonymMap, bool onlyIfUnchanged = false, global::System.Threading.CancellationToken cancellationToken = default)
        {
            global::Azure.Search.Documents.Indexes.Models.SynonymMap synonymMap_ = synonymMap;
            bool onlyIfUnchanged_ = onlyIfUnchanged;
            global::System.Threading.CancellationToken cancellationToken_ = cancellationToken;
            var result_1590442821 = _Instance.CreateOrUpdateSynonymMap(synonymMap_, onlyIfUnchanged_, cancellationToken_);
            return result_1590442821;
        }

        public virtual global::System.Threading.Tasks.Task<global::Azure.Response<global::Azure.Search.Documents.Indexes.Models.SynonymMap>> CreateOrUpdateSynonymMapAsync(global::Azure.Search.Documents.Indexes.Models.SynonymMap synonymMap, bool onlyIfUnchanged = false, global::System.Threading.CancellationToken cancellationToken = default)
        {
            global::Azure.Search.Documents.Indexes.Models.SynonymMap synonymMap_ = synonymMap;
            bool onlyIfUnchanged_ = onlyIfUnchanged;
            global::System.Threading.CancellationToken cancellationToken_ = cancellationToken;
            var result__1943740197 = _Instance.CreateOrUpdateSynonymMapAsync(synonymMap_, onlyIfUnchanged_, cancellationToken_);
            return result__1943740197;
        }

        public virtual global::Azure.Response DeleteSynonymMap(string synonymMapName, global::System.Threading.CancellationToken cancellationToken = default)
        {
            string synonymMapName_ = synonymMapName;
            global::System.Threading.CancellationToken cancellationToken_ = cancellationToken;
            var result_391338208 = _Instance.DeleteSynonymMap(synonymMapName_, cancellationToken_);
            return result_391338208;
        }

        public virtual global::System.Threading.Tasks.Task<global::Azure.Response> DeleteSynonymMapAsync(string synonymMapName, global::System.Threading.CancellationToken cancellationToken = default)
        {
            string synonymMapName_ = synonymMapName;
            global::System.Threading.CancellationToken cancellationToken_ = cancellationToken;
            var result__1264012664 = _Instance.DeleteSynonymMapAsync(synonymMapName_, cancellationToken_);
            return result__1264012664;
        }

        public virtual global::Azure.Response DeleteSynonymMap(global::Azure.Search.Documents.Indexes.Models.SynonymMap synonymMap, bool onlyIfUnchanged = false, global::System.Threading.CancellationToken cancellationToken = default)
        {
            global::Azure.Search.Documents.Indexes.Models.SynonymMap synonymMap_ = synonymMap;
            bool onlyIfUnchanged_ = onlyIfUnchanged;
            global::System.Threading.CancellationToken cancellationToken_ = cancellationToken;
            var result_391338208 = _Instance.DeleteSynonymMap(synonymMap_, onlyIfUnchanged_, cancellationToken_);
            return result_391338208;
        }

        public virtual global::System.Threading.Tasks.Task<global::Azure.Response> DeleteSynonymMapAsync(global::Azure.Search.Documents.Indexes.Models.SynonymMap synonymMap, bool onlyIfUnchanged = false, global::System.Threading.CancellationToken cancellationToken = default)
        {
            global::Azure.Search.Documents.Indexes.Models.SynonymMap synonymMap_ = synonymMap;
            bool onlyIfUnchanged_ = onlyIfUnchanged;
            global::System.Threading.CancellationToken cancellationToken_ = cancellationToken;
            var result__1264012664 = _Instance.DeleteSynonymMapAsync(synonymMap_, onlyIfUnchanged_, cancellationToken_);
            return result__1264012664;
        }

        public virtual global::Azure.Response<global::System.Collections.Generic.IReadOnlyList<global::Azure.Search.Documents.Indexes.Models.SynonymMap>> GetSynonymMaps(global::System.Threading.CancellationToken cancellationToken = default)
        {
            global::System.Threading.CancellationToken cancellationToken_ = cancellationToken;
            var result_850421152 = _Instance.GetSynonymMaps(cancellationToken_);
            return result_850421152;
        }

        public virtual global::System.Threading.Tasks.Task<global::Azure.Response<global::System.Collections.Generic.IReadOnlyList<global::Azure.Search.Documents.Indexes.Models.SynonymMap>>> GetSynonymMapsAsync(global::System.Threading.CancellationToken cancellationToken = default)
        {
            global::System.Threading.CancellationToken cancellationToken_ = cancellationToken;
            var result_2122168116 = _Instance.GetSynonymMapsAsync(cancellationToken_);
            return result_2122168116;
        }

        public virtual global::Azure.Response<global::System.Collections.Generic.IReadOnlyList<string>> GetSynonymMapNames(global::System.Threading.CancellationToken cancellationToken = default)
        {
            global::System.Threading.CancellationToken cancellationToken_ = cancellationToken;
            var result_1489647659 = _Instance.GetSynonymMapNames(cancellationToken_);
            return result_1489647659;
        }

        public virtual global::System.Threading.Tasks.Task<global::Azure.Response<global::System.Collections.Generic.IReadOnlyList<string>>> GetSynonymMapNamesAsync(global::System.Threading.CancellationToken cancellationToken = default)
        {
            global::System.Threading.CancellationToken cancellationToken_ = cancellationToken;
            var result__1808553803 = _Instance.GetSynonymMapNamesAsync(cancellationToken_);
            return result__1808553803;
        }

        public virtual global::Azure.Response<global::System.Collections.Generic.IReadOnlyList<global::Azure.Search.Documents.Indexes.Models.AnalyzedTokenInfo>> AnalyzeText(string indexName, global::Azure.Search.Documents.Indexes.Models.AnalyzeTextOptions options, global::System.Threading.CancellationToken cancellationToken = default)
        {
            string indexName_ = indexName;
            global::Azure.Search.Documents.Indexes.Models.AnalyzeTextOptions options_ = options;
            global::System.Threading.CancellationToken cancellationToken_ = cancellationToken;
            var result_1701057949 = _Instance.AnalyzeText(indexName_, options_, cancellationToken_);
            return result_1701057949;
        }

        public virtual global::System.Threading.Tasks.Task<global::Azure.Response<global::System.Collections.Generic.IReadOnlyList<global::Azure.Search.Documents.Indexes.Models.AnalyzedTokenInfo>>> AnalyzeTextAsync(string indexName, global::Azure.Search.Documents.Indexes.Models.AnalyzeTextOptions options, global::System.Threading.CancellationToken cancellationToken = default)
        {
            string indexName_ = indexName;
            global::Azure.Search.Documents.Indexes.Models.AnalyzeTextOptions options_ = options;
            global::System.Threading.CancellationToken cancellationToken_ = cancellationToken;
            var result_402725703 = _Instance.AnalyzeTextAsync(indexName_, options_, cancellationToken_);
            return result_402725703;
        }

        public virtual global::Azure.Response<global::Azure.Search.Documents.Indexes.Models.KnowledgeBase> CreateKnowledgeBase(global::Azure.Search.Documents.Indexes.Models.KnowledgeBase knowledgeBase, global::System.Threading.CancellationToken cancellationToken = default)
        {
            global::Azure.Search.Documents.Indexes.Models.KnowledgeBase knowledgeBase_ = knowledgeBase;
            global::System.Threading.CancellationToken cancellationToken_ = cancellationToken;
            var result_191818039 = _Instance.CreateKnowledgeBase(knowledgeBase_, cancellationToken_);
            return result_191818039;
        }

        public virtual global::System.Threading.Tasks.Task<global::Azure.Response<global::Azure.Search.Documents.Indexes.Models.KnowledgeBase>> CreateKnowledgeBaseAsync(global::Azure.Search.Documents.Indexes.Models.KnowledgeBase knowledgeBase, global::System.Threading.CancellationToken cancellationToken = default)
        {
            global::Azure.Search.Documents.Indexes.Models.KnowledgeBase knowledgeBase_ = knowledgeBase;
            global::System.Threading.CancellationToken cancellationToken_ = cancellationToken;
            var result__1868928399 = _Instance.CreateKnowledgeBaseAsync(knowledgeBase_, cancellationToken_);
            return result__1868928399;
        }

        public virtual global::Azure.Response<global::Azure.Search.Documents.Indexes.Models.KnowledgeBase> CreateOrUpdateKnowledgeBase(global::Azure.Search.Documents.Indexes.Models.KnowledgeBase knowledgeBase, bool onlyIfUnchanged = false, global::System.Threading.CancellationToken cancellationToken = default)
        {
            global::Azure.Search.Documents.Indexes.Models.KnowledgeBase knowledgeBase_ = knowledgeBase;
            bool onlyIfUnchanged_ = onlyIfUnchanged;
            global::System.Threading.CancellationToken cancellationToken_ = cancellationToken;
            var result__851498677 = _Instance.CreateOrUpdateKnowledgeBase(knowledgeBase_, onlyIfUnchanged_, cancellationToken_);
            return result__851498677;
        }

        public virtual global::System.Threading.Tasks.Task<global::Azure.Response<global::Azure.Search.Documents.Indexes.Models.KnowledgeBase>> CreateOrUpdateKnowledgeBaseAsync(global::Azure.Search.Documents.Indexes.Models.KnowledgeBase knowledgeBase, bool onlyIfUnchanged = false, global::System.Threading.CancellationToken cancellationToken = default)
        {
            global::Azure.Search.Documents.Indexes.Models.KnowledgeBase knowledgeBase_ = knowledgeBase;
            bool onlyIfUnchanged_ = onlyIfUnchanged;
            global::System.Threading.CancellationToken cancellationToken_ = cancellationToken;
            var result__1726079551 = _Instance.CreateOrUpdateKnowledgeBaseAsync(knowledgeBase_, onlyIfUnchanged_, cancellationToken_);
            return result__1726079551;
        }

        public virtual global::Azure.Response DeleteKnowledgeBase(global::Azure.Search.Documents.Indexes.Models.KnowledgeBase knowledgeBase, bool onlyIfUnchanged = false, global::System.Threading.CancellationToken cancellationToken = default)
        {
            global::Azure.Search.Documents.Indexes.Models.KnowledgeBase knowledgeBase_ = knowledgeBase;
            bool onlyIfUnchanged_ = onlyIfUnchanged;
            global::System.Threading.CancellationToken cancellationToken_ = cancellationToken;
            var result_1873838950 = _Instance.DeleteKnowledgeBase(knowledgeBase_, onlyIfUnchanged_, cancellationToken_);
            return result_1873838950;
        }

        public virtual global::System.Threading.Tasks.Task<global::Azure.Response> DeleteKnowledgeBaseAsync(global::Azure.Search.Documents.Indexes.Models.KnowledgeBase knowledgeBase, bool onlyIfUnchanged = false, global::System.Threading.CancellationToken cancellationToken = default)
        {
            global::Azure.Search.Documents.Indexes.Models.KnowledgeBase knowledgeBase_ = knowledgeBase;
            bool onlyIfUnchanged_ = onlyIfUnchanged;
            global::System.Threading.CancellationToken cancellationToken_ = cancellationToken;
            var result_1653894238 = _Instance.DeleteKnowledgeBaseAsync(knowledgeBase_, onlyIfUnchanged_, cancellationToken_);
            return result_1653894238;
        }

        public virtual global::Azure.Response<global::Azure.Search.Documents.Indexes.Models.KnowledgeSource> CreateKnowledgeSource(global::Azure.Search.Documents.Indexes.Models.KnowledgeSource knowledgeSource, global::System.Threading.CancellationToken cancellationToken = default)
        {
            global::Azure.Search.Documents.Indexes.Models.KnowledgeSource knowledgeSource_ = knowledgeSource;
            global::System.Threading.CancellationToken cancellationToken_ = cancellationToken;
            var result__2025136409 = _Instance.CreateKnowledgeSource(knowledgeSource_, cancellationToken_);
            return result__2025136409;
        }

        public virtual global::System.Threading.Tasks.Task<global::Azure.Response<global::Azure.Search.Documents.Indexes.Models.KnowledgeSource>> CreateKnowledgeSourceAsync(global::Azure.Search.Documents.Indexes.Models.KnowledgeSource knowledgeSource, global::System.Threading.CancellationToken cancellationToken = default)
        {
            global::Azure.Search.Documents.Indexes.Models.KnowledgeSource knowledgeSource_ = knowledgeSource;
            global::System.Threading.CancellationToken cancellationToken_ = cancellationToken;
            var result_2108037481 = _Instance.CreateKnowledgeSourceAsync(knowledgeSource_, cancellationToken_);
            return result_2108037481;
        }

        public virtual global::Azure.Response<global::Azure.Search.Documents.Indexes.Models.KnowledgeSource> CreateOrUpdateKnowledgeSource(global::Azure.Search.Documents.Indexes.Models.KnowledgeSource knowledgeSource, bool onlyIfUnchanged = false, global::System.Threading.CancellationToken cancellationToken = default)
        {
            global::Azure.Search.Documents.Indexes.Models.KnowledgeSource knowledgeSource_ = knowledgeSource;
            bool onlyIfUnchanged_ = onlyIfUnchanged;
            global::System.Threading.CancellationToken cancellationToken_ = cancellationToken;
            var result__81945373 = _Instance.CreateOrUpdateKnowledgeSource(knowledgeSource_, onlyIfUnchanged_, cancellationToken_);
            return result__81945373;
        }

        public virtual global::System.Threading.Tasks.Task<global::Azure.Response<global::Azure.Search.Documents.Indexes.Models.KnowledgeSource>> CreateOrUpdateKnowledgeSourceAsync(global::Azure.Search.Documents.Indexes.Models.KnowledgeSource knowledgeSource, bool onlyIfUnchanged = false, global::System.Threading.CancellationToken cancellationToken = default)
        {
            global::Azure.Search.Documents.Indexes.Models.KnowledgeSource knowledgeSource_ = knowledgeSource;
            bool onlyIfUnchanged_ = onlyIfUnchanged;
            global::System.Threading.CancellationToken cancellationToken_ = cancellationToken;
            var result_433254273 = _Instance.CreateOrUpdateKnowledgeSourceAsync(knowledgeSource_, onlyIfUnchanged_, cancellationToken_);
            return result_433254273;
        }

        public virtual global::Azure.Response DeleteKnowledgeSource(global::Azure.Search.Documents.Indexes.Models.KnowledgeSource knowledgeSource, bool onlyIfUnchanged = false, global::System.Threading.CancellationToken cancellationToken = default)
        {
            global::Azure.Search.Documents.Indexes.Models.KnowledgeSource knowledgeSource_ = knowledgeSource;
            bool onlyIfUnchanged_ = onlyIfUnchanged;
            global::System.Threading.CancellationToken cancellationToken_ = cancellationToken;
            var result__1693336290 = _Instance.DeleteKnowledgeSource(knowledgeSource_, onlyIfUnchanged_, cancellationToken_);
            return result__1693336290;
        }

        public virtual global::System.Threading.Tasks.Task<global::Azure.Response> DeleteKnowledgeSourceAsync(global::Azure.Search.Documents.Indexes.Models.KnowledgeSource knowledgeSource, bool onlyIfUnchanged = false, global::System.Threading.CancellationToken cancellationToken = default)
        {
            global::Azure.Search.Documents.Indexes.Models.KnowledgeSource knowledgeSource_ = knowledgeSource;
            bool onlyIfUnchanged_ = onlyIfUnchanged;
            global::System.Threading.CancellationToken cancellationToken_ = cancellationToken;
            var result__676719858 = _Instance.DeleteKnowledgeSourceAsync(knowledgeSource_, onlyIfUnchanged_, cancellationToken_);
            return result__676719858;
        }


        public SearchIndexClientProxy(global::Azure.Search.Documents.Indexes.SearchIndexClient instance)
        {
            _Instance = instance;
            
        }
    }
}
#nullable restore