//----------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by https://github.com/StefH/ProxyInterfaceSourceGenerator.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//----------------------------------------------------------------------------------------

#nullable enable
using System;

namespace ProxyInterfaceSourceGeneratorTests.Source.AzureSearch
{
    public partial interface IAzureSearchIndexClient
    {
        global::Azure.Search.Documents.Indexes.SearchIndexClient _Instance { get; }

        global::Azure.Core.Pipeline.HttpPipeline Pipeline { get; }

        global::System.Uri Endpoint { get; }

        string ServiceName { get; }

        global::Azure.Response DeleteSynonymMap(string synonymMapName, global::Azure.MatchConditions matchConditions, global::Azure.RequestContext context);

        global::System.Threading.Tasks.Task<global::Azure.Response> DeleteSynonymMapAsync(string synonymMapName, global::Azure.MatchConditions matchConditions, global::Azure.RequestContext context);

        global::Azure.Response DeleteSynonymMap(string synonymMapName, global::Azure.MatchConditions matchConditions = null!, global::System.Threading.CancellationToken cancellationToken = default);

        global::System.Threading.Tasks.Task<global::Azure.Response> DeleteSynonymMapAsync(string synonymMapName, global::Azure.MatchConditions matchConditions = null!, global::System.Threading.CancellationToken cancellationToken = default);

        global::Azure.Response GetSynonymMap(string synonymMapName, global::Azure.RequestContext context);

        global::System.Threading.Tasks.Task<global::Azure.Response> GetSynonymMapAsync(string synonymMapName, global::Azure.RequestContext context);

        global::Azure.Response<global::Azure.Search.Documents.Indexes.Models.SynonymMap> GetSynonymMap(string synonymMapName, global::System.Threading.CancellationToken cancellationToken = default);

        global::System.Threading.Tasks.Task<global::Azure.Response<global::Azure.Search.Documents.Indexes.Models.SynonymMap>> GetSynonymMapAsync(string synonymMapName, global::System.Threading.CancellationToken cancellationToken = default);

        global::Azure.Response CreateSynonymMap(global::Azure.Core.RequestContent content, global::Azure.RequestContext context = null!);

        global::System.Threading.Tasks.Task<global::Azure.Response> CreateSynonymMapAsync(global::Azure.Core.RequestContent content, global::Azure.RequestContext context = null!);

        global::Azure.Response<global::Azure.Search.Documents.Indexes.Models.SynonymMap> CreateSynonymMap(global::Azure.Search.Documents.Indexes.Models.SynonymMap synonymMap, global::System.Threading.CancellationToken cancellationToken = default);

        global::System.Threading.Tasks.Task<global::Azure.Response<global::Azure.Search.Documents.Indexes.Models.SynonymMap>> CreateSynonymMapAsync(global::Azure.Search.Documents.Indexes.Models.SynonymMap synonymMap, global::System.Threading.CancellationToken cancellationToken = default);

        global::Azure.Response DeleteIndex(string indexName, global::Azure.MatchConditions matchConditions, global::Azure.RequestContext context);

        global::System.Threading.Tasks.Task<global::Azure.Response> DeleteIndexAsync(string indexName, global::Azure.MatchConditions matchConditions, global::Azure.RequestContext context);

        global::Azure.Response DeleteIndex(string indexName, global::Azure.MatchConditions matchConditions = null!, global::System.Threading.CancellationToken cancellationToken = default);

        global::System.Threading.Tasks.Task<global::Azure.Response> DeleteIndexAsync(string indexName, global::Azure.MatchConditions matchConditions = null!, global::System.Threading.CancellationToken cancellationToken = default);

        global::Azure.Response GetIndex(string indexName, global::Azure.RequestContext context);

        global::System.Threading.Tasks.Task<global::Azure.Response> GetIndexAsync(string indexName, global::Azure.RequestContext context);

        global::Azure.Response<global::Azure.Search.Documents.Indexes.Models.SearchIndex> GetIndex(string indexName, global::System.Threading.CancellationToken cancellationToken = default);

        global::System.Threading.Tasks.Task<global::Azure.Response<global::Azure.Search.Documents.Indexes.Models.SearchIndex>> GetIndexAsync(string indexName, global::System.Threading.CancellationToken cancellationToken = default);

        global::Azure.Pageable<global::System.BinaryData> GetIndexes(global::Azure.RequestContext context);

        global::Azure.AsyncPageable<global::System.BinaryData> GetIndexesAsync(global::Azure.RequestContext context);

        global::Azure.Pageable<global::System.BinaryData> GetIndexesWithSelectedProperties(global::System.Collections.Generic.IEnumerable<string> @select, global::Azure.RequestContext context);

        global::Azure.AsyncPageable<global::System.BinaryData> GetIndexesWithSelectedPropertiesAsync(global::System.Collections.Generic.IEnumerable<string> @select, global::Azure.RequestContext context);

        global::Azure.Pageable<global::Azure.Search.Documents.Indexes.Models.SearchIndexResponse> GetIndexesWithSelectedProperties(global::System.Collections.Generic.IEnumerable<string> @select = null!, global::System.Threading.CancellationToken cancellationToken = default);

        global::Azure.AsyncPageable<global::Azure.Search.Documents.Indexes.Models.SearchIndexResponse> GetIndexesWithSelectedPropertiesAsync(global::System.Collections.Generic.IEnumerable<string> @select = null!, global::System.Threading.CancellationToken cancellationToken = default);

        global::Azure.Response CreateIndex(global::Azure.Core.RequestContent content, global::Azure.RequestContext context = null!);

        global::System.Threading.Tasks.Task<global::Azure.Response> CreateIndexAsync(global::Azure.Core.RequestContent content, global::Azure.RequestContext context = null!);

        global::Azure.Response<global::Azure.Search.Documents.Indexes.Models.SearchIndex> CreateIndex(global::Azure.Search.Documents.Indexes.Models.SearchIndex index, global::System.Threading.CancellationToken cancellationToken = default);

        global::System.Threading.Tasks.Task<global::Azure.Response<global::Azure.Search.Documents.Indexes.Models.SearchIndex>> CreateIndexAsync(global::Azure.Search.Documents.Indexes.Models.SearchIndex index, global::System.Threading.CancellationToken cancellationToken = default);

        global::Azure.Response GetIndexStatistics(string indexName, global::Azure.RequestContext context);

        global::System.Threading.Tasks.Task<global::Azure.Response> GetIndexStatisticsAsync(string indexName, global::Azure.RequestContext context);

        global::Azure.Response<global::Azure.Search.Documents.Indexes.Models.SearchIndexStatistics> GetIndexStatistics(string indexName, global::System.Threading.CancellationToken cancellationToken = default);

        global::System.Threading.Tasks.Task<global::Azure.Response<global::Azure.Search.Documents.Indexes.Models.SearchIndexStatistics>> GetIndexStatisticsAsync(string indexName, global::System.Threading.CancellationToken cancellationToken = default);

        global::Azure.Response AnalyzeText(string indexName, global::Azure.Core.RequestContent content, global::Azure.RequestContext context = null!);

        global::System.Threading.Tasks.Task<global::Azure.Response> AnalyzeTextAsync(string indexName, global::Azure.Core.RequestContent content, global::Azure.RequestContext context = null!);

        global::Azure.Response DeleteAlias(string aliasName, global::Azure.MatchConditions matchConditions, global::Azure.RequestContext context);

        global::System.Threading.Tasks.Task<global::Azure.Response> DeleteAliasAsync(string aliasName, global::Azure.MatchConditions matchConditions, global::Azure.RequestContext context);

        global::Azure.Response DeleteAlias(string aliasName, global::Azure.MatchConditions matchConditions = null!, global::System.Threading.CancellationToken cancellationToken = default);

        global::System.Threading.Tasks.Task<global::Azure.Response> DeleteAliasAsync(string aliasName, global::Azure.MatchConditions matchConditions = null!, global::System.Threading.CancellationToken cancellationToken = default);

        global::Azure.Response GetAlias(string aliasName, global::Azure.RequestContext context);

        global::System.Threading.Tasks.Task<global::Azure.Response> GetAliasAsync(string aliasName, global::Azure.RequestContext context);

        global::Azure.Response<global::Azure.Search.Documents.Indexes.Models.SearchAlias> GetAlias(string aliasName, global::System.Threading.CancellationToken cancellationToken = default);

        global::System.Threading.Tasks.Task<global::Azure.Response<global::Azure.Search.Documents.Indexes.Models.SearchAlias>> GetAliasAsync(string aliasName, global::System.Threading.CancellationToken cancellationToken = default);

        global::Azure.Pageable<global::System.BinaryData> GetAliases(global::Azure.RequestContext context);

        global::Azure.AsyncPageable<global::System.BinaryData> GetAliasesAsync(global::Azure.RequestContext context);

        global::Azure.Pageable<global::Azure.Search.Documents.Indexes.Models.SearchAlias> GetAliases(global::System.Threading.CancellationToken cancellationToken = default);

        global::Azure.AsyncPageable<global::Azure.Search.Documents.Indexes.Models.SearchAlias> GetAliasesAsync(global::System.Threading.CancellationToken cancellationToken = default);

        global::Azure.Response CreateAlias(global::Azure.Core.RequestContent content, global::Azure.RequestContext context = null!);

        global::System.Threading.Tasks.Task<global::Azure.Response> CreateAliasAsync(global::Azure.Core.RequestContent content, global::Azure.RequestContext context = null!);

        global::Azure.Response<global::Azure.Search.Documents.Indexes.Models.SearchAlias> CreateAlias(global::Azure.Search.Documents.Indexes.Models.SearchAlias @alias, global::System.Threading.CancellationToken cancellationToken = default);

        global::System.Threading.Tasks.Task<global::Azure.Response<global::Azure.Search.Documents.Indexes.Models.SearchAlias>> CreateAliasAsync(global::Azure.Search.Documents.Indexes.Models.SearchAlias @alias, global::System.Threading.CancellationToken cancellationToken = default);

        global::Azure.Response DeleteKnowledgeBase(string knowledgeBaseName, global::Azure.MatchConditions matchConditions, global::Azure.RequestContext context);

        global::System.Threading.Tasks.Task<global::Azure.Response> DeleteKnowledgeBaseAsync(string knowledgeBaseName, global::Azure.MatchConditions matchConditions, global::Azure.RequestContext context);

        global::Azure.Response DeleteKnowledgeBase(string knowledgeBaseName, global::Azure.MatchConditions matchConditions = null!, global::System.Threading.CancellationToken cancellationToken = default);

        global::System.Threading.Tasks.Task<global::Azure.Response> DeleteKnowledgeBaseAsync(string knowledgeBaseName, global::Azure.MatchConditions matchConditions = null!, global::System.Threading.CancellationToken cancellationToken = default);

        global::Azure.Response GetKnowledgeBase(string knowledgeBaseName, global::Azure.RequestContext context);

        global::System.Threading.Tasks.Task<global::Azure.Response> GetKnowledgeBaseAsync(string knowledgeBaseName, global::Azure.RequestContext context);

        global::Azure.Response<global::Azure.Search.Documents.Indexes.Models.KnowledgeBase> GetKnowledgeBase(string knowledgeBaseName, global::System.Threading.CancellationToken cancellationToken = default);

        global::System.Threading.Tasks.Task<global::Azure.Response<global::Azure.Search.Documents.Indexes.Models.KnowledgeBase>> GetKnowledgeBaseAsync(string knowledgeBaseName, global::System.Threading.CancellationToken cancellationToken = default);

        global::Azure.Pageable<global::System.BinaryData> GetKnowledgeBases(global::Azure.RequestContext context);

        global::Azure.AsyncPageable<global::System.BinaryData> GetKnowledgeBasesAsync(global::Azure.RequestContext context);

        global::Azure.Pageable<global::Azure.Search.Documents.Indexes.Models.KnowledgeBase> GetKnowledgeBases(global::System.Threading.CancellationToken cancellationToken = default);

        global::Azure.AsyncPageable<global::Azure.Search.Documents.Indexes.Models.KnowledgeBase> GetKnowledgeBasesAsync(global::System.Threading.CancellationToken cancellationToken = default);

        global::Azure.Response CreateKnowledgeBase(global::Azure.Core.RequestContent content, global::Azure.RequestContext context = null!);

        global::System.Threading.Tasks.Task<global::Azure.Response> CreateKnowledgeBaseAsync(global::Azure.Core.RequestContent content, global::Azure.RequestContext context = null!);

        global::Azure.Response DeleteKnowledgeSource(string sourceName, global::Azure.MatchConditions matchConditions, global::Azure.RequestContext context);

        global::System.Threading.Tasks.Task<global::Azure.Response> DeleteKnowledgeSourceAsync(string sourceName, global::Azure.MatchConditions matchConditions, global::Azure.RequestContext context);

        global::Azure.Response DeleteKnowledgeSource(string sourceName, global::Azure.MatchConditions matchConditions = null!, global::System.Threading.CancellationToken cancellationToken = default);

        global::System.Threading.Tasks.Task<global::Azure.Response> DeleteKnowledgeSourceAsync(string sourceName, global::Azure.MatchConditions matchConditions = null!, global::System.Threading.CancellationToken cancellationToken = default);

        global::Azure.Response GetKnowledgeSource(string sourceName, global::Azure.RequestContext context);

        global::System.Threading.Tasks.Task<global::Azure.Response> GetKnowledgeSourceAsync(string sourceName, global::Azure.RequestContext context);

        global::Azure.Response<global::Azure.Search.Documents.Indexes.Models.KnowledgeSource> GetKnowledgeSource(string sourceName, global::System.Threading.CancellationToken cancellationToken = default);

        global::System.Threading.Tasks.Task<global::Azure.Response<global::Azure.Search.Documents.Indexes.Models.KnowledgeSource>> GetKnowledgeSourceAsync(string sourceName, global::System.Threading.CancellationToken cancellationToken = default);

        global::Azure.Pageable<global::System.BinaryData> GetKnowledgeSources(global::Azure.RequestContext context);

        global::Azure.AsyncPageable<global::System.BinaryData> GetKnowledgeSourcesAsync(global::Azure.RequestContext context);

        global::Azure.Pageable<global::Azure.Search.Documents.Indexes.Models.KnowledgeSource> GetKnowledgeSources(global::System.Threading.CancellationToken cancellationToken = default);

        global::Azure.AsyncPageable<global::Azure.Search.Documents.Indexes.Models.KnowledgeSource> GetKnowledgeSourcesAsync(global::System.Threading.CancellationToken cancellationToken = default);

        global::Azure.Response CreateKnowledgeSource(global::Azure.Core.RequestContent content, global::Azure.RequestContext context = null!);

        global::System.Threading.Tasks.Task<global::Azure.Response> CreateKnowledgeSourceAsync(global::Azure.Core.RequestContent content, global::Azure.RequestContext context = null!);

        global::Azure.Response GetKnowledgeSourceStatus(string sourceName, global::Azure.RequestContext context);

        global::System.Threading.Tasks.Task<global::Azure.Response> GetKnowledgeSourceStatusAsync(string sourceName, global::Azure.RequestContext context);

        global::Azure.Response<global::Azure.Search.Documents.KnowledgeBases.Models.KnowledgeSourceStatus> GetKnowledgeSourceStatus(string sourceName, global::System.Threading.CancellationToken cancellationToken = default);

        global::System.Threading.Tasks.Task<global::Azure.Response<global::Azure.Search.Documents.KnowledgeBases.Models.KnowledgeSourceStatus>> GetKnowledgeSourceStatusAsync(string sourceName, global::System.Threading.CancellationToken cancellationToken = default);

        global::Azure.Response GetServiceStatistics(global::Azure.RequestContext context);

        global::System.Threading.Tasks.Task<global::Azure.Response> GetServiceStatisticsAsync(global::Azure.RequestContext context);

        global::Azure.Response<global::Azure.Search.Documents.Indexes.Models.SearchServiceStatistics> GetServiceStatistics(global::System.Threading.CancellationToken cancellationToken = default);

        global::System.Threading.Tasks.Task<global::Azure.Response<global::Azure.Search.Documents.Indexes.Models.SearchServiceStatistics>> GetServiceStatisticsAsync(global::System.Threading.CancellationToken cancellationToken = default);

        global::Azure.Response<global::Azure.Search.Documents.Indexes.Models.SearchAlias> CreateOrUpdateAlias(global::Azure.Search.Documents.Indexes.Models.SearchAlias @alias, bool onlyIfUnchanged = false, global::System.Threading.CancellationToken cancellationToken = default);

        global::System.Threading.Tasks.Task<global::Azure.Response<global::Azure.Search.Documents.Indexes.Models.SearchAlias>> CreateOrUpdateAliasAsync(global::Azure.Search.Documents.Indexes.Models.SearchAlias @alias, bool onlyIfUnchanged = false, global::System.Threading.CancellationToken cancellationToken = default);

        global::Azure.Response DeleteAlias(global::Azure.Search.Documents.Indexes.Models.SearchAlias @alias, bool onlyIfUnchanged = false, global::System.Threading.CancellationToken cancellationToken = default);

        global::System.Threading.Tasks.Task<global::Azure.Response> DeleteAliasAsync(global::Azure.Search.Documents.Indexes.Models.SearchAlias @alias, bool onlyIfUnchanged = false, global::System.Threading.CancellationToken cancellationToken = default);

        global::Azure.Search.Documents.SearchClient GetSearchClient(string indexName);

        global::Azure.Response<global::Azure.Search.Documents.Indexes.Models.SearchIndex> CreateOrUpdateIndex(global::Azure.Search.Documents.Indexes.Models.SearchIndex index, bool allowIndexDowntime = false, bool onlyIfUnchanged = false, global::System.Threading.CancellationToken cancellationToken = default);

        global::System.Threading.Tasks.Task<global::Azure.Response<global::Azure.Search.Documents.Indexes.Models.SearchIndex>> CreateOrUpdateIndexAsync(global::Azure.Search.Documents.Indexes.Models.SearchIndex index, bool allowIndexDowntime = false, bool onlyIfUnchanged = false, global::System.Threading.CancellationToken cancellationToken = default);

        global::Azure.Response DeleteIndex(string indexName, global::System.Threading.CancellationToken cancellationToken = default);

        global::System.Threading.Tasks.Task<global::Azure.Response> DeleteIndexAsync(string indexName, global::System.Threading.CancellationToken cancellationToken = default);

        global::Azure.Response DeleteIndex(global::Azure.Search.Documents.Indexes.Models.SearchIndex index, bool onlyIfUnchanged = false, global::System.Threading.CancellationToken cancellationToken = default);

        global::System.Threading.Tasks.Task<global::Azure.Response> DeleteIndexAsync(global::Azure.Search.Documents.Indexes.Models.SearchIndex index, bool onlyIfUnchanged = false, global::System.Threading.CancellationToken cancellationToken = default);

        global::Azure.Pageable<string> GetIndexNames(global::System.Threading.CancellationToken cancellationToken = default);

        global::Azure.AsyncPageable<string> GetIndexNamesAsync(global::System.Threading.CancellationToken cancellationToken = default);

        global::Azure.Pageable<global::Azure.Search.Documents.Indexes.Models.SearchIndex> GetIndexes(global::System.Threading.CancellationToken cancellationToken = default);

        global::Azure.AsyncPageable<global::Azure.Search.Documents.Indexes.Models.SearchIndex> GetIndexesAsync(global::System.Threading.CancellationToken cancellationToken = default);

        global::Azure.Response<global::Azure.Search.Documents.Indexes.Models.SynonymMap> CreateOrUpdateSynonymMap(global::Azure.Search.Documents.Indexes.Models.SynonymMap synonymMap, bool onlyIfUnchanged = false, global::System.Threading.CancellationToken cancellationToken = default);

        global::System.Threading.Tasks.Task<global::Azure.Response<global::Azure.Search.Documents.Indexes.Models.SynonymMap>> CreateOrUpdateSynonymMapAsync(global::Azure.Search.Documents.Indexes.Models.SynonymMap synonymMap, bool onlyIfUnchanged = false, global::System.Threading.CancellationToken cancellationToken = default);

        global::Azure.Response DeleteSynonymMap(string synonymMapName, global::System.Threading.CancellationToken cancellationToken = default);

        global::System.Threading.Tasks.Task<global::Azure.Response> DeleteSynonymMapAsync(string synonymMapName, global::System.Threading.CancellationToken cancellationToken = default);

        global::Azure.Response DeleteSynonymMap(global::Azure.Search.Documents.Indexes.Models.SynonymMap synonymMap, bool onlyIfUnchanged = false, global::System.Threading.CancellationToken cancellationToken = default);

        global::System.Threading.Tasks.Task<global::Azure.Response> DeleteSynonymMapAsync(global::Azure.Search.Documents.Indexes.Models.SynonymMap synonymMap, bool onlyIfUnchanged = false, global::System.Threading.CancellationToken cancellationToken = default);

        global::Azure.Response<global::System.Collections.Generic.IReadOnlyList<global::Azure.Search.Documents.Indexes.Models.SynonymMap>> GetSynonymMaps(global::System.Threading.CancellationToken cancellationToken = default);

        global::System.Threading.Tasks.Task<global::Azure.Response<global::System.Collections.Generic.IReadOnlyList<global::Azure.Search.Documents.Indexes.Models.SynonymMap>>> GetSynonymMapsAsync(global::System.Threading.CancellationToken cancellationToken = default);

        global::Azure.Response<global::System.Collections.Generic.IReadOnlyList<string>> GetSynonymMapNames(global::System.Threading.CancellationToken cancellationToken = default);

        global::System.Threading.Tasks.Task<global::Azure.Response<global::System.Collections.Generic.IReadOnlyList<string>>> GetSynonymMapNamesAsync(global::System.Threading.CancellationToken cancellationToken = default);

        global::Azure.Response<global::System.Collections.Generic.IReadOnlyList<global::Azure.Search.Documents.Indexes.Models.AnalyzedTokenInfo>> AnalyzeText(string indexName, global::Azure.Search.Documents.Indexes.Models.AnalyzeTextOptions options, global::System.Threading.CancellationToken cancellationToken = default);

        global::System.Threading.Tasks.Task<global::Azure.Response<global::System.Collections.Generic.IReadOnlyList<global::Azure.Search.Documents.Indexes.Models.AnalyzedTokenInfo>>> AnalyzeTextAsync(string indexName, global::Azure.Search.Documents.Indexes.Models.AnalyzeTextOptions options, global::System.Threading.CancellationToken cancellationToken = default);

        global::Azure.Response<global::Azure.Search.Documents.Indexes.Models.KnowledgeBase> CreateKnowledgeBase(global::Azure.Search.Documents.Indexes.Models.KnowledgeBase knowledgeBase, global::System.Threading.CancellationToken cancellationToken = default);

        global::System.Threading.Tasks.Task<global::Azure.Response<global::Azure.Search.Documents.Indexes.Models.KnowledgeBase>> CreateKnowledgeBaseAsync(global::Azure.Search.Documents.Indexes.Models.KnowledgeBase knowledgeBase, global::System.Threading.CancellationToken cancellationToken = default);

        global::Azure.Response<global::Azure.Search.Documents.Indexes.Models.KnowledgeBase> CreateOrUpdateKnowledgeBase(global::Azure.Search.Documents.Indexes.Models.KnowledgeBase knowledgeBase, bool onlyIfUnchanged = false, global::System.Threading.CancellationToken cancellationToken = default);

        global::System.Threading.Tasks.Task<global::Azure.Response<global::Azure.Search.Documents.Indexes.Models.KnowledgeBase>> CreateOrUpdateKnowledgeBaseAsync(global::Azure.Search.Documents.Indexes.Models.KnowledgeBase knowledgeBase, bool onlyIfUnchanged = false, global::System.Threading.CancellationToken cancellationToken = default);

        global::Azure.Response DeleteKnowledgeBase(global::Azure.Search.Documents.Indexes.Models.KnowledgeBase knowledgeBase, bool onlyIfUnchanged = false, global::System.Threading.CancellationToken cancellationToken = default);

        global::System.Threading.Tasks.Task<global::Azure.Response> DeleteKnowledgeBaseAsync(global::Azure.Search.Documents.Indexes.Models.KnowledgeBase knowledgeBase, bool onlyIfUnchanged = false, global::System.Threading.CancellationToken cancellationToken = default);

        global::Azure.Response<global::Azure.Search.Documents.Indexes.Models.KnowledgeSource> CreateKnowledgeSource(global::Azure.Search.Documents.Indexes.Models.KnowledgeSource knowledgeSource, global::System.Threading.CancellationToken cancellationToken = default);

        global::System.Threading.Tasks.Task<global::Azure.Response<global::Azure.Search.Documents.Indexes.Models.KnowledgeSource>> CreateKnowledgeSourceAsync(global::Azure.Search.Documents.Indexes.Models.KnowledgeSource knowledgeSource, global::System.Threading.CancellationToken cancellationToken = default);

        global::Azure.Response<global::Azure.Search.Documents.Indexes.Models.KnowledgeSource> CreateOrUpdateKnowledgeSource(global::Azure.Search.Documents.Indexes.Models.KnowledgeSource knowledgeSource, bool onlyIfUnchanged = false, global::System.Threading.CancellationToken cancellationToken = default);

        global::System.Threading.Tasks.Task<global::Azure.Response<global::Azure.Search.Documents.Indexes.Models.KnowledgeSource>> CreateOrUpdateKnowledgeSourceAsync(global::Azure.Search.Documents.Indexes.Models.KnowledgeSource knowledgeSource, bool onlyIfUnchanged = false, global::System.Threading.CancellationToken cancellationToken = default);

        global::Azure.Response DeleteKnowledgeSource(global::Azure.Search.Documents.Indexes.Models.KnowledgeSource knowledgeSource, bool onlyIfUnchanged = false, global::System.Threading.CancellationToken cancellationToken = default);

        global::System.Threading.Tasks.Task<global::Azure.Response> DeleteKnowledgeSourceAsync(global::Azure.Search.Documents.Indexes.Models.KnowledgeSource knowledgeSource, bool onlyIfUnchanged = false, global::System.Threading.CancellationToken cancellationToken = default);
    }
}
#nullable restore