//----------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by https://github.com/StefH/ProxyInterfaceSourceGenerator.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//----------------------------------------------------------------------------------------

#nullable enable
using System;

namespace ProxyInterfaceDemo.Depth
{
    public partial interface IDestroyable
    {
        global::ProxyInterfaceDemo.Depth.Destroyable _Instance { get; }


    }
}
#nullable restore