name: "Check Build"

on:
  pull_request:
    
jobs: 
  deploy:
    runs-on: ubuntu-latest
      
    steps:
      - name: Checkout Project
        uses: actions/checkout@v4
        
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x
          
      - name: Restore dependencies
        run: dotnet restore
        
      - name: Build
        run: dotnet build --configuration Debug --no-restore 
        
      - name: Test
        run: dotnet test --no-build --configuration Debug --verbosity normal